const ARMOR_PASSIVES = [
  {
    displayName: "高级过滤",
    type: "Equipment",
    category: "armor",
    tags: ["ArmorPassive"],
    warbondCode: "warbond10",
    internalName: "advancedfiltration",
    imageURL: "advancedfiltration.png",
    tier: "c",
    index: 0,
  },
  {
    displayName: "环境适应",
    type: "Equipment",
    category: "armor",
    tags: ["ArmorPassive"],
    warbondCode: "warbond18",
    internalName: "acclimated",
    imageURL: "inflammable.png",
    tier: "b",
    index: 1,
  },
  {
    displayName: "民主保护",
    type: "Equipment",
    category: "armor",
    tags: ["ArmorPassive"],
    warbondCode: "none",
    internalName: "democracyprotects",
    imageURL: "democracyprotects.png",
    tier: "a",
    index: 2,
  },
  {
    displayName: "电导",
    type: "Equipment",
    category: "armor",
    tags: ["ArmorPassive"],
    warbondCode: "warbond5",
    internalName: "electricalconduit",
    imageURL: "electricalconduit.png",
    tier: "c",
    index: 3,
  },
  {
    displayName: "工程套件",
    type: "Equipment",
    category: "armor",
    tags: ["ArmorPassive"],
    warbondCode: "warbond3",
    internalName: "engineeringkit",
    imageURL: "engineeringkit.png",
    tier: "a",
    index: 4,
  },
  {
    displayName: "额外护垫",
    type: "Equipment",
    category: "armor",
    tags: ["ArmorPassive"],
    warbondCode: "none",
    internalName: "extrapadding",
    imageURL: "extrapadding.png",
    tier: "b",
    index: 5,
  },
  {
    displayName: "强化",
    type: "Equipment",
    category: "armor",
    tags: ["ArmorPassive"],
    warbondCode: "warbond6",
    internalName: "fortified",
    imageURL: "fortified.png",
    tier: "a",
    index: 6,
  },
  {
    displayName: "防火",
    type: "Equipment",
    category: "armor",
    tags: ["ArmorPassive"],
    warbondCode: "warbond9",
    internalName: "inflammable",
    imageURL: "inflammable.png",
    tier: "b",
    index: 7,
  },
  {
    displayName: "医疗包",
    type: "Equipment",
    category: "armor",
    tags: ["ArmorPassive"],
    warbondCode: "warbond3",
    internalName: "medkit",
    imageURL: "medkit.png",
    tier: "a",
    index: 8,
  },
  {
    displayName: "巅峰体能",
    type: "Equipment",
    category: "armor",
    tags: ["ArmorPassive"],
    warbondCode: "warbond8",
    internalName: "peakphysique",
    imageURL: "peakphysique.png",
    tier: "a",
    index: 9,
  },
  {
    displayName: "侦察",
    type: "Equipment",
    category: "armor",
    tags: ["ArmorPassive"],
    warbondCode: "warbond3",
    internalName: "scout",
    imageURL: "scout.png",
    tier: "b",
    index: 10,
  },
  {
    displayName: "伺服辅助",
    type: "Equipment",
    category: "armor",
    tags: ["ArmorPassive"],
    warbondCode: "warbond4",
    internalName: "servoassisted",
    imageURL: "servoassisted.png",
    tier: "b",
    index: 11,
  },
  {
    displayName: "坚定不移",
    type: "Equipment",
    category: "armor",
    tags: ["ArmorPassive"],
    warbondCode: "warbond11",
    internalName: "unflinching",
    imageURL: "unflinching.png",
    tier: "b",
    index: 12,
  },
  {
    displayName: "攻城准备",
    type: "Equipment",
    category: "armor",
    tags: ["ArmorPassive"],
    warbondCode: "warbond12",
    internalName: "siegeready",
    imageURL: "siegeready.png",
    tier: "s",
    index: 13,
  },
  {
    displayName: "集成炸药",
    type: "Equipment",
    category: "armor",
    tags: ["ArmorPassive"],
    warbondCode: "warbond13",
    internalName: "integratedexplosives",
    imageURL: "integratedexplosives.png",
    tier: "b",
    index: 14,
  },
  {
    displayName: "枪手",
    type: "Equipment",
    category: "armor",
    tags: ["ArmorPassive"],
    warbondCode: "warbond14",
    internalName: "gunslinger",
    imageURL: "gunslinger.png",
    tier: "b",
    index: 15,
  },
  {
    displayName: "强化肩章",
    type: "Equipment",
    category: "armor",
    tags: ["ArmorPassive"],
    warbondCode: "warbond15",
    internalName: "reinforcedepaulettes",
    imageURL: "reinforcedepaulettes.png",
    tier: "a",
    index: 16,
  },
  {
    displayName: "防弹护垫",
    type: "Equipment",
    category: "armor",
    tags: ["ArmorPassive"],
    warbondCode: "warbond16",
    internalName: "ballisticpadding",
    imageURL: "ballisticpadding.png",
    tier: "b",
    index: 17,
  },
  {
    displayName: "肾上腺素除颤器",
    type: "Equipment",
    category: "armor",
    tags: ["ArmorPassive"],
    warbondCode: "warbond17",
    internalName: "adrenodefibrillator",
    imageURL: "adrenodefibrillator.png",
    tier: "b",
    index: 18,
  },
  {
    displayName: "脚先着地",
    type: "Equipment",
    category: "armor",
    tags: ["ArmorPassive"],
    warbondCode: "warbond19",
    internalName: "feetfirst",
    imageURL: "feetfirst.png",
    tier: "b",
    index: 19,
  },
  {
    displayName: "沙漠风暴者",
    type: "Equipment",
    category: "armor",
    tags: ["ArmorPassive"],
    warbondCode: "warbond20",
    internalName: "desertstormer",
    imageURL: "desertstormer.png",
    tier: "b",
    index: 20,
  },
  {
    displayName: "坚如磐石",
    type: "Equipment",
    category: "armor",
    tags: ["ArmorPassive"],
    warbondCode: "warbond21",
    internalName: "rocksolid",
    imageURL: "rocksolid.webp",
    tier: "a",
    index: 21,
  },
  {
    displayName: "降低信号",
    type: "Equipment",
    category: "armor",
    tags: ["ArmorPassive"],
    warbondCode: "warbond22",
    internalName: "reducedsignature",
    imageURL: "reducedsignature.webp",
    tier: "b",
    index: 22,
  },
  {
    displayName: "补充肾上腺素",
    type: "Equipment",
    category: "armor",
    tags: ["ArmorPassive"],
    warbondCode: "warbond23",
    internalName: "supplementaryadrenaline",
    imageURL: "supplementaryadrenaline.webp",
    tier: "b",
    index: 23,
  },
  {
    displayName: "防震护垫",
    type: "Equipment",
    category: "armor",
    tags: ["ArmorPassive"],
    warbondCode: "warbond24",
    internalName: "concussivepadding",
    imageURL: "concussivepadding.webp",
    tier: "b",
    index: 24,
  },
  {
    displayName: "氧气发生器",
    type: "Equipment",
    category: "armor",
    tags: ["ArmorPassive"],
    warbondCode: "warbond25",
    internalName: "oxygenator",
    imageURL: "oxygenator.webp",
    tier: "b",
    index: 25,
  },
];

// s: 1
// a: 7
// b: 13
// c: 2
