const ARMOR_SIZES = [
  {
    displayName: "轻型护甲",
    type: "Equipment",
    category: "armor",
    tags: ["ArmorSize"],
    warbondCode: "",
    internalName: "light",
    imageURL: "",
    tier: "b",
  },
  {
    displayName: "中型护甲",
    type: "Equipment",
    category: "armor",
    tags: ["ArmorSize"],
    warbondCode: "",
    internalName: "medium",
    imageURL: "",
    tier: "b",
  },
  {
    displayName: "重型护甲",
    type: "Equipment",
    category: "armor",
    tags: ["ArmorSize"],
    warbondCode: "",
    internalName: "heavy",
    imageURL: "",
    tier: "b",
  },
];
