const BOOSTERS = [
  {
    displayName: '专业撤离飞行员',
    type: 'Equipment',
    category: 'booster',
    tags: [],
    warbondCode: 'warbond6',
    internalName: 'expertextractionpilot',
    imageURL: 'expertextractionpilot.png',
    tier: 'c',
    index: 0,
  },
  {
    displayName: '死亡冲刺',
    type: 'Equipment',
    category: 'booster',
    tags: [],
    warbondCode: 'warbond11',
    internalName: 'deadsprint',
    imageURL: 'deadsprint.png',
    tier: 'b',
    index: 1,
  },
  {
    displayName: '武装补给舱',
    type: 'Equipment',
    category: 'booster',
    tags: [],
    warbondCode: 'warbond12',
    internalName: 'armedresupplypods',
    imageURL: 'armedresupplypods.png',
    tier: 'b',
    index: 2,
  },
  {
    displayName: '实验性注射',
    type: 'Equipment',
    category: 'booster',
    tags: [],
    warbondCode: 'warbond8',
    internalName: 'experimentalinfusion',
    imageURL: 'experimentalinfusion.png',
    tier: 's',
    index: 3,
  },
  {
    displayName: '激励电击',
    type: 'Equipment',
    category: 'booster',
    tags: [],
    warbondCode: 'warbond7',
    internalName: 'motivationalshocks',
    imageURL: 'motivationalshocks.png',
    tier: 'b',
    index: 4,
  },
  {
    displayName: '灵活增援预算',
    type: 'Equipment',
    category: 'booster',
    tags: [],
    warbondCode: 'warbond4',
    internalName: 'flexiblereinforcementbudget',
    imageURL: 'flexiblereinforcementbudget.png',
    tier: 'c',
    index: 5,
  },
  {
    displayName: '地狱舱空间优化',
    type: 'Equipment',
    category: 'booster',
    tags: [],
    warbondCode: 'warbond3',
    internalName: 'hellpodspaceoptimization',
    imageURL: 'hellpodspaceoptimization.png',
    tier: 's',
    index: 6,
  },
  {
    displayName: '增加增援预算',
    type: 'Equipment',
    category: 'booster',
    tags: [],
    warbondCode: 'warbond3',
    internalName: 'increasedreinforcementbudget',
    imageURL: 'increasedreinforcementbudget.png',
    tier: 'b',
    index: 7,
  },
  {
    displayName: '定位混乱',
    type: 'Equipment',
    category: 'booster',
    tags: [],
    warbondCode: 'warbond5',
    internalName: 'localizationconfusion',
    imageURL: 'localizationconfusion.png',
    tier: 'b',
    index: 8,
  },
  {
    displayName: '肌肉增强',
    type: 'Equipment',
    category: 'booster',
    tags: [],
    warbondCode: 'warbond3',
    internalName: 'muscleenhancement',
    imageURL: 'muscleenhancement.png',
    tier: 'a',
    index: 9,
  },
  {
    displayName: '耐力增强',
    type: 'Equipment',
    category: 'booster',
    tags: [],
    warbondCode: 'warbond3',
    internalName: 'staminaenhancement',
    imageURL: 'staminaenhancement.png',
    tier: 's',
    index: 10,
  },
  {
    displayName: '无人机侦察',
    type: 'Equipment',
    category: 'booster',
    tags: [],
    warbondCode: 'warbond3',
    internalName: 'uavrecon',
    imageURL: 'uavrecon.png',
    tier: 'b',
    index: 11,
  },
  {
    displayName: '活力增强',
    type: 'Equipment',
    category: 'booster',
    tags: [],
    warbondCode: 'warbond3',
    internalName: 'vitalityenhancement',
    imageURL: 'vitalityenhancement.png',
    tier: 's',
    index: 12,
  },
  {
    displayName: '燃烧弹地狱舱',
    type: 'Equipment',
    category: 'booster',
    tags: [],
    warbondCode: 'warbond9',
    internalName: 'firebombhellpods',
    imageURL: 'firebombhellpods.png',
    tier: 'c',
    index: 13,
  },
  {
    displayName: '样本提取器',
    type: 'Equipment',
    category: 'booster',
    tags: [],
    warbondCode: 'warbond14',
    internalName: 'sampleextricator',
    imageURL: 'sampleextricator.png',
    tier: 'c',
    index: 14,
  },
  {
    displayName: '样本扫描器',
    type: 'Equipment',
    category: 'booster',
    tags: [],
    warbondCode: 'warbond15',
    internalName: 'samplescanner',
    imageURL: 'samplescanner.png',
    tier: 'c',
    index: 15,
  },
  {
    displayName: '眩晕舱',
    type: 'Equipment',
    category: 'booster',
    tags: [],
    warbondCode: 'warbond16',
    internalName: 'stunpods',
    imageURL: 'stunpods.png',
    tier: 'b',
    index: 16,
  },
  {
    displayName: '隐蔽投放',
    type: 'Equipment',
    category: 'booster',
    tags: [],
    warbondCode: 'warbond22',
    internalName: 'concealedinsertion',
    imageURL: 'concealedinsertion.webp',
    tier: 'b',
    index: 17,
  },
];

// s: 4
// a: 1
// b: 6
// c: 5
