const CAPES = [
  {
    displayName: "破敌者",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
    index: 0,
  },
  {
    displayName: "人民意志",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond0",
    internalName: "willofthepeople",
    imageURL: "willofthepeople.webp",
    tier: "b",
    index: 1,
  },
  {
    displayName: "独立使者",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond3",
    internalName: "independencebringer",
    imageURL: "independencebringer.webp",
    tier: "b",
    index: 2,
  },
  {
    displayName: "自由先驱",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond3",
    internalName: "libertysherald",
    imageURL: "libertysherald.webp",
    tier: "b",
    index: 3,
  },
  {
    displayName: "逆转潮汐",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond3",
    internalName: "tideturner",
    imageURL: "tideturner.webp",
    tier: "b",
    index: 4,
  },
  {
    displayName: "星辰与选举权",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond3",
    internalName: "thecapeofstarsandsuffrage",
    imageURL: "thecapeofstarsandsuffrage.webp",
    tier: "b",
    index: 5,
  },
  {
    displayName: "无瑕忠诚",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond3",
    internalName: "unblemishedallegiance",
    imageURL: "unblemishedallegiance.webp",
    tier: "b",
    index: 6,
  },
  {
    displayName: "审判日",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond3",
    internalName: "judgmentday",
    imageURL: "judgmentday.webp",
    tier: "b",
    index: 7,
  },
  {
    displayName: "荣誉之巅",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond3",
    internalName: "crestinghonor",
    imageURL: "crestinghonor.webp",
    tier: "b",
    index: 8,
  },
  {
    displayName: "真公民披风",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond3",
    internalName: "mantleoftruecitizenship",
    imageURL: "mantleoftruecitizenship.webp",
    tier: "b",
    index: 9,
  },
  {
    displayName: "燃烧的善人",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond3",
    internalName: "blazingsamaritan",
    imageURL: "blazingsamaritan.webp",
    tier: "b",
    index: 10,
  },
  {
    displayName: "永恒自由之光",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond3",
    internalName: "lightofeternalliberty",
    imageURL: "lightofeternalliberty.webp",
    tier: "b",
    index: 11,
  },
  {
    displayName: "暴君猎手",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond4",
    internalName: "tyranthunter",
    imageURL: "tyranthunter.webp",
    tier: "b",
    index: 12,
  },
  {
    displayName: "后代感恩斗篷",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond4",
    internalName: "cloakofposteritysgratitude",
    imageURL: "cloakofposteritysgratitude.webp",
    tier: "b",
    index: 13,
  },
  {
    displayName: "荣耀帷幕",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond4",
    internalName: "drapeofglory",
    imageURL: "drapeofglory.webp",
    tier: "b",
    index: 14,
  },
  {
    displayName: "诚信堡垒",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond3",
    internalName: "bastionofintegrity",
    imageURL: "bastionofintegrity.webp",
    tier: "b",
    index: 15,
  },
  {
    displayName: "机器人杀手",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond5",
    internalName: "botslayer",
    imageURL: "botslayer.webp",
    tier: "b",
    index: 16,
  },
  {
    displayName: "殉道之王",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond5",
    internalName: "martyrisrex",
    imageURL: "martyrisrex.webp",
    tier: "b",
    index: 17,
  },
  {
    displayName: "湮灭特工",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond5",
    internalName: "agentofoblivion",
    imageURL: "agentofoblivion.webp",
    tier: "b",
    index: 18,
  },
  {
    displayName: "英烈复仇",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "fallenherosvengeance",
    imageURL: "fallenherosvengeance.webp",
    tier: "b",
    index: 19,
  },
  {
    displayName: "真平等先驱",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond6",
    internalName: "harbingeroftrueequality",
    imageURL: "harbingeroftrueequality.webp",
    tier: "b",
    index: 20,
  },
  {
    displayName: "飞鹰之怒",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond6",
    internalName: "eaglesfury",
    imageURL: "eaglesfury.webp",
    tier: "b",
    index: 21,
  },
  {
    displayName: "自由织锦",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond6",
    internalName: "freedomstapestry",
    imageURL: "freedomstapestry.webp",
    tier: "b",
    index: 22,
  },
  {
    displayName: "异见者噩梦",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond7",
    internalName: "dissidentsnightmare",
    imageURL: "dissidentsnightmare.webp",
    tier: "b",
    index: 23,
  },
  {
    displayName: "正当占领者",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond20",
    internalName: "rightfuloccupier",
    imageURL: "rightfuloccupier.webp",
    tier: "b",
    index: 24,
  },
  {
    displayName: "永恒荣光之翼",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond7",
    internalName: "pinionsofeverlastingglory",
    imageURL: "pinionsofeverlastingglory.webp",
    tier: "b",
    index: 25,
  },
  {
    displayName: "风行者",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond20",
    internalName: "windsweptwayfinder",
    imageURL: "windsweptwayfinder.webp",
    tier: "b",
    index: 26,
  },
  {
    displayName: "神圣选票勋章",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond7",
    internalName: "orderoftheveneratedballot",
    imageURL: "orderoftheveneratedballot.webp",
    tier: "b",
    index: 27,
  },
  {
    displayName: "血红獠牙印记",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond8",
    internalName: "markofthecrimsonfang",
    imageURL: "markofthecrimsonfang.webp",
    tier: "b",
    index: 28,
  },
  {
    displayName: "行刑者华盖",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond8",
    internalName: "executionerscanopy",
    imageURL: "executionerscanopy.webp",
    tier: "b",
    index: 29,
  },
  {
    displayName: "净化日食",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond9",
    internalName: "purifyingeclipse",
    imageURL: "purifyingeclipse.webp",
    tier: "b",
    index: 30,
  },
  {
    displayName: "突破口",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond9",
    internalName: "thebreach",
    imageURL: "thebreach.webp",
    tier: "b",
    index: 31,
  },
  {
    displayName: "安全距离标准",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond10",
    internalName: "standardofsafedistance",
    imageURL: "standardofsafedistance.webp",
    tier: "b",
    index: 32,
  },
  {
    displayName: "零号病人纪念",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond10",
    internalName: "patientzerosremembrance",
    imageURL: "patientzerosremembrance.webp",
    tier: "b",
    index: 33,
  },
  {
    displayName: "黑暗掩护",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond1",
    internalName: "coverofdarkness",
    imageURL: "coverofdarkness.webp",
    tier: "b",
    index: 34,
  },
  {
    displayName: "举报者之傲",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond11",
    internalName: "prideofthewhistleblower",
    imageURL: "prideofthewhistleblower.webp",
    tier: "b",
    index: 35,
  },
  {
    displayName: "无瑕美德证明",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond11",
    internalName: "proofoffaultlessvirtue",
    imageURL: "proofoffaultlessvirtue.webp",
    tier: "b",
    index: 36,
  },
  {
    displayName: "石铸毅力",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond1",
    internalName: "stonewroughtperserverance",
    imageURL: "stonewroughtperserverance.webp",
    tier: "b",
    index: 37,
  },
  {
    displayName: "钢筋决心大氅",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond12",
    internalName: "greatcloakofrebarresolve",
    imageURL: "greatcloakofrebarresolve.webp",
    tier: "b",
    index: 38,
  },
  {
    displayName: "黄线守护者",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond12",
    internalName: "holderoftheyellowline",
    imageURL: "holderoftheyellowline.webp",
    tier: "b",
    index: 39,
  },
  {
    displayName: "我们臂中的力量",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond18",
    internalName: "strengthinourarms",
    imageURL: "strengthinourarms.webp",
    tier: "b",
    index: 40,
  },
  {
    displayName: "我们梦想的守护者",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond18",
    internalName: "defenderofourdream",
    imageURL: "defenderofourdream.webp",
    tier: "b",
    index: 41,
  },
  {
    displayName: "自由愿景",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond1",
    internalName: "visionoffreedom",
    imageURL: "visionoffreedom.webp",
    tier: "b",
    index: 42,
  },
  {
    displayName: "永恒日冕",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond1",
    internalName: "eternalcorona",
    imageURL: "eternalcorona.webp",
    tier: "b",
    index: 43,
  },
  {
    displayName: "自由之书",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond13",
    internalName: "freliberam",
    imageURL: "freliberam.webp",
    tier: "b",
    index: 44,
  },
  {
    displayName: "经由民主",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond13",
    internalName: "perdemocrasum",
    imageURL: "perdemocrasum.webp",
    tier: "b",
    index: 45,
  },
  {
    displayName: "自由之眼",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "eyeoffreedom",
    imageURL: "eyeoffreedom.webp",
    tier: "b",
    index: 46,
  },
  {
    displayName: "自由徽记",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "emblemoffreedom",
    imageURL: "emblemoffreedom.webp",
    tier: "b",
    index: 47,
  },
  {
    displayName: "勇者浪客面纱",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond1",
    internalName: "veilofthevalorousvagabond",
    imageURL: "veilofthevalorousvagabond.webp",
    tier: "b",
    index: 48,
  },
  {
    displayName: "赏金收割者",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond14",
    internalName: "reaperofbounties",
    imageURL: "reaperofbounties.webp",
    tier: "b",
    index: 49,
  },
  {
    displayName: "弹带之道",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond14",
    internalName: "wayofthebandolier",
    imageURL: "wayofthebandolier.webp",
    tier: "b",
    index: 50,
  },
  {
    displayName: "普遍共识之印",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond1",
    internalName: "sealofgeneralconsensus",
    imageURL: "sealofgeneralconsensus.webp",
    tier: "b",
    index: 51,
  },
  {
    displayName: "联邦拥抱",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond15",
    internalName: "federationsembrace",
    imageURL: "federationsembrace.webp",
    tier: "b",
    index: 52,
  },
  {
    displayName: "谦逊华服",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond15",
    internalName: "humbleregalia",
    imageURL: "humbleregalia.webp",
    tier: "b",
    index: 53,
  },
  {
    displayName: "秩序徽章",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond1",
    internalName: "badgeoforder",
    imageURL: "badgeoforder.webp",
    tier: "b",
    index: 54,
  },
  {
    displayName: "米兰达的遗产",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond16",
    internalName: "mirandaslegacy",
    imageURL: "mirandaslegacy.webp",
    tier: "b",
    index: 55,
  },
  {
    displayName: "母鹰之翼",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond16",
    internalName: "mothereagleswings",
    imageURL: "mothereagleswings.webp",
    tier: "b",
    index: 56,
  },
  {
    displayName: "心灵守护者",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "protectoroftheheart",
    imageURL: "protectoroftheheart.webp",
    tier: "b",
    index: 57,
  },
  {
    displayName: "自由支柱",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "pillarsoffreedom",
    imageURL: "pillarsoffreedom.webp",
    tier: "b",
    index: 58,
  },
  {
    displayName: "光辉引导者",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond17",
    internalName: "conductorofbrilliance",
    imageURL: "conductorofbrilliance.webp",
    tier: "b",
    index: 59,
  },
  {
    displayName: "凌驾诡计",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond17",
    internalName: "overartificetriumphant",
    imageURL: "overartificetriumphant.webp",
    tier: "b",
    index: 60,
  },
  {
    displayName: "赤裸蓝图",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond1",
    internalName: "schemalaidbare",
    imageURL: "schemalaidbare.webp",
    tier: "b",
    index: 61,
  },
  {
    displayName: "Ingress-81",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "ingress81",
    imageURL: "ingress81.webp",
    tier: "b",
    index: 62,
  },
  {
    displayName: "荣耀传家宝",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond19",
    internalName: "honoredheirloom",
    imageURL: "honoredheirloom.webp",
    tier: "b",
    index: 63,
  },
  {
    displayName: "密探之眼",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond19",
    internalName: "eyeoftheclandestine",
    imageURL: "eyeoftheclandestine.webp",
    tier: "b",
    index: 64,
  },
  {
    displayName: "真实意识形态",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "veridicalideology",
    imageURL: "veridicalideology.webp",
    tier: "b",
    index: 65,
  },
  {
    displayName: "蟒蛇印记",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "markoftheconstrictor",
    imageURL: "markoftheconstrictor.webp",
    tier: "b",
    index: 66,
  },
  {
    displayName: "撕裂敌人",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foerentasunder",
    imageURL: "foerentasunder.webp",
    tier: "b",
    index: 67,
  },
  {
    displayName: "伐林者帆布",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "deforesterssailcloth",
    imageURL: "deforesterssailcloth.webp",
    tier: "b",
    index: 68,
  },
  {
    displayName: "对抗暴君阴云",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "againstthetyrantcloud",
    imageURL: "againstthetyrantcloud.webp",
    tier: "b",
    index: 69,
  },
  {
    displayName: "清算之欢呼",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "reckoningscheer",
    imageURL: "reckoningscheer.webp",
    tier: "b",
    index: 70,
  },
  {
    displayName: "深渊之柱",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond22",
    internalName: "pillaroftheabyss",
    imageURL: "pillaroftheabyss.webp",
    tier: "b",
    index: 71,
  },
  {
    displayName: "三角测量面纱",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond22",
    internalName: "triangulationveil",
    imageURL: "triangulationveil.webp",
    tier: "b",
    index: 72,
  },
  {
    displayName: "镀金羽毛",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond1",
    internalName: "gildedquill",
    imageURL: "gildedquill.webp",
    tier: "b",
    index: 73,
  },
  {
    displayName: "时尚破布",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond23",
    internalName: "ragsofthefashionable",
    imageURL: "ragsofthefashionable.webp",
    tier: "b",
    index: 74,
  },
  {
    displayName: "楔形三角帽",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond23",
    internalName: "wedgefultricorn",
    imageURL: "wedgefultricorn.webp",
    tier: "b",
    index: 75,
  },
  {
    displayName: "忠诚雷鸣蹄",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond1",
    internalName: "thunderinghoovesofloyalty",
    imageURL: "thunderinghoovesofloyalty.webp",
    tier: "b",
    index: 76,
  },
  {
    displayName: "自由之眼",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond1",
    internalName: "eyeofliberty",
    imageURL: "eyeofliberty.webp",
    tier: "b",
    index: 77,
  },
  {
    displayName: "辛劳尊严",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond24",
    internalName: "dignityoftoil",
    imageURL: "dignityoftoil.webp",
    tier: "b",
    index: 78,
  },
  {
    displayName: "纯洁者之冠",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond24",
    internalName: "crestoftheunsullied",
    imageURL: "crestoftheunsullied.webp",
    tier: "b",
    index: 79,
  },
  {
    displayName: "消耗战见证",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond1",
    internalName: "testamenttoattrition",
    imageURL: "testamenttoattrition.webp",
    tier: "b",
    index: 80,
  },
  {
    displayName: "自由精神亮片",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond25",
    internalName: "freespiritedspangles",
    imageURL: "freespiritedspangles.webp",
    tier: "b",
    index: 81,
  },
  {
    displayName: "警惕同胞",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond25",
    internalName: "watchfulcompatriot",
    imageURL: "watchfulcompatriot.webp",
    tier: "b",
    index: 82,
  },
  {
    displayName: "最高贵载荷图解",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond1",
    internalName: "diagramofthenoblestpayload",
    imageURL: "diagramofthenoblestpayload.webp",
    tier: "b",
    index: 83,
  },
];
