const PRIMARIES = [
  {
    displayName: '解放者',
    type: 'Equipment',
    category: 'primary',
    tags: ['AssaultRifle', 'ap2'],
    warbondCode: 'none',
    internalName: 'ar23liberator',
    imageURL: 'ar23liberator.png',
    antitank: false,
    tier: 'b',
    index: 0,
  },
  {
    displayName: '穿甲解放',
    type: 'Equipment',
    category: 'primary',
    tags: ['AssaultRifle', 'ap3'],
    warbondCode: 'warbond3',
    internalName: 'ar23pliberatorpenetrator',
    imageURL: 'ar23pliberatorpenetrator.png',
    antitank: false,
    tier: 'a',
    index: 1,
  },
  {
    displayName: '震荡解放',
    type: 'Equipment',
    category: 'primary',
    tags: ['AssaultRifle', 'ap2'],
    warbondCode: 'warbond4',
    internalName: 'ar23cliberatorconcussive',
    imageURL: 'ar23cliberatorconcussive.png',
    antitank: false,
    tier: 'b',
    index: 2,
  },
  {
    displayName: '卡宾解放',
    type: 'Equipment',
    category: 'primary',
    tags: ['AssaultRifle', 'ap2'],
    warbondCode: 'warbond8',
    internalName: 'ar23aliberatorcarbine',
    imageURL: 'ar23aliberatorcarbine.png',
    antitank: false,
    tier: 'a',
    index: 3,
  },
  {
    displayName: '审判者',
    type: 'Equipment',
    category: 'primary',
    tags: ['AssaultRifle', 'ap3'],
    warbondCode: 'warbond6',
    internalName: 'br14adjudicator',
    imageURL: 'br14adjudicator.png',
    antitank: false,
    tier: 'a',
    index: 4,
  },
  {
    displayName: 'StA-52 突击步枪',
    type: 'Equipment',
    category: 'primary',
    tags: ['AssaultRifle', 'ap2'],
    warbondCode: 'warbond18',
    internalName: 'sta52assaultrifle',
    imageURL: 'sta52assaultrifle.png',
    antitank: false,
    tier: 'b',
    index: 5,
  },
  {
    displayName: '安抚者',
    type: 'Equipment',
    category: 'primary',
    tags: ['AssaultRifle', 'ap3', 'stun'],
    warbondCode: 'warbond16',
    internalName: 'ar32pacifier',
    imageURL: 'ar32pacifier.png',
    antitank: false,
    tier: 'b',
    index: 6,
  },
  {
    displayName: '肉锤',
    type: 'Equipment',
    category: 'primary',
    tags: ['AssaultRifle', 'ap2'],
    warbondCode: 'warbond7',
    internalName: 'ar61tenderizer',
    imageURL: 'ar61tenderizer.png',
    antitank: false,
    tier: 'a',
    index: 7,
  },
  {
    displayName: 'MA5C 突击步枪',
    type: 'Equipment',
    category: 'primary',
    tags: ['AssaultRifle', 'ap3'],
    warbondCode: 'warbond19',
    internalName: 'ma5c',
    imageURL: 'ma5c.png',
    antitank: false,
    tier: 'b',
    index: 8,
  },
  {
    displayName: 'AR-2 郊狼',
    type: 'Equipment',
    category: 'primary',
    tags: ['AssaultRifle', 'ap3', 'fire'],
    warbondCode: 'warbond20',
    internalName: 'ar2coyote',
    imageURL: 'ar2coyote.png',
    antitank: false,
    tier: 's',
    index: 9,
  },
  {
    displayName: '一二',
    type: 'Equipment',
    category: 'primary',
    tags: ['AssaultRifle', 'ap2', 'ap3', 'explosive'],
    warbondCode: 'warbond21',
    internalName: 'onetwo',
    imageURL: 'onetwo.webp',
    antitank: false,
    tier: 'b',
    index: 10,
  },
  {
    displayName: '消音者',
    type: 'Equipment',
    category: 'primary',
    tags: ['AssaultRifle', 'ap2', 'suppressed'],
    warbondCode: 'warbond22',
    internalName: 'ar59suppressor',
    imageURL: 'ar59suppressor.webp',
    antitank: false,
    tier: 'b',
    index: 11,
  },
  {
    displayName: '防卫者',
    type: 'Equipment',
    category: 'primary',
    tags: ['SubmachineGun', 'ap2', 'onehanded'],
    warbondCode: 'warbond3',
    internalName: 'smg37defender',
    imageURL: 'smg37defender.png',
    antitank: false,
    tier: 'b',
    index: 12,
  },
  {
    displayName: '猛击者',
    type: 'Equipment',
    category: 'primary',
    tags: ['SubmachineGun', 'ap2', 'onehanded'],
    warbondCode: 'warbond7',
    internalName: 'smg72pummeler',
    imageURL: 'smg72pummeler.png',
    antitank: false,
    tier: 'b',
    index: 13,
  },
  {
    displayName: '惩戒者',
    type: 'Equipment',
    category: 'primary',
    tags: ['Submachinegun', 'ap3'],
    warbondCode: 'warbond11',
    internalName: 'smg32reprimand',
    imageURL: 'smg32reprimand.png',
    antitank: false,
    tier: 'a',
    index: 14,
  },
  {
    displayName: 'StA-11 冲锋枪',
    type: 'Equipment',
    category: 'primary',
    tags: ['Submachinegun', 'ap2', 'onehanded'],
    warbondCode: 'warbond18',
    internalName: 'sta11smg',
    imageURL: 'sta11smg.png',
    antitank: false,
    tier: 'b',
    index: 15,
  },
  {
    displayName: '骑士',
    type: 'Equipment',
    category: 'primary',
    tags: ['SubmachineGun', 'ap2', 'onehanded'],
    warbondCode: 'warbond0',
    internalName: 'mp98knight',
    imageURL: 'mp98knight.png',
    antitank: false,
    tier: 'b',
    index: 16,
  },
  {
    displayName: 'M7S 冲锋枪',
    type: 'Equipment',
    category: 'primary',
    tags: ['SubmachineGun', 'ap2', 'onehanded'],
    warbondCode: 'warbond19',
    internalName: 'm7s',
    imageURL: 'm7s.png',
    antitank: false,
    tier: 'b',
    index: 17,
  },
  {
    displayName: '双重自由',
    type: 'Equipment',
    category: 'primary',
    tags: ['Shotgun', 'ap3'],
    warbondCode: 'warbond1',
    internalName: 'doublefreedom',
    imageURL: 'doublefreedom.webp',
    antitank: false,
    tier: 'b',
    index: 18,
  },
  {
    displayName: '制裁者',
    type: 'Equipment',
    category: 'primary',
    tags: ['Shotgun', 'ap2'],
    warbondCode: 'warbond3',
    internalName: 'sg8punisher',
    imageURL: 'sg8punisher.png',
    antitank: false,
    tier: 'b',
    index: 19,
  },
  {
    displayName: '野炊者',
    type: 'Equipment',
    category: 'primary',
    tags: ['Shotgun', 'ap2', 'fire'],
    warbondCode: 'warbond9',
    internalName: 'sg451cookout',
    imageURL: 'sg451cookout.png',
    antitank: false,
    tier: 'a',
    index: 20,
  },
  {
    displayName: '重炮手',
    type: 'Equipment',
    category: 'primary',
    tags: ['Shotgun', 'ap3'],
    warbondCode: 'warbond3',
    internalName: 'sg8sslugger',
    imageURL: 'sg8sslugger.png',
    antitank: false,
    tier: 'b',
    index: 21,
  },
  {
    displayName: '破裂',
    type: 'Equipment',
    category: 'primary',
    tags: ['Shotgun', 'ap2'],
    warbondCode: 'warbond3',
    internalName: 'sg225breaker',
    imageURL: 'sg225breaker.png',
    antitank: false,
    tier: 'b',
    index: 22,
  },
  {
    displayName: '高燃破裂',
    type: 'Equipment',
    category: 'primary',
    tags: ['Shotgun', 'ap2', 'fire'],
    warbondCode: 'warbond4',
    internalName: 'sg225iebreakerincendiary',
    imageURL: 'sg225iebreakerincendiary.png',
    antitank: false,
    tier: 'a',
    index: 23,
  },
  {
    displayName: '祷告破裂',
    type: 'Equipment',
    category: 'primary',
    tags: ['Shotgun', 'ap2'],
    warbondCode: 'warbond3',
    internalName: 'sg225spbreakerspraynpray',
    imageURL: 'sg225spbreakerspraynpray.png',
    antitank: false,
    tier: 'b',
    index: 24,
  },
  {
    displayName: '停顿者',
    type: 'Equipment',
    category: 'primary',
    tags: ['Shotgun', 'ap2', 'ap3', 'stun'],
    warbondCode: 'warbond11',
    internalName: 'sg20halt',
    imageURL: 'sg20halt.png',
    antitank: false,
    tier: 'a',
    index: 25,
  },
  {
    displayName: 'M90A 霰弹枪',
    type: 'Equipment',
    category: 'primary',
    tags: ['Shotgun', 'ap2'],
    warbondCode: 'warbond19',
    internalName: 'm90a',
    imageURL: 'm90a.png',
    antitank: false,
    tier: 'a',
    index: 26,
  },
  {
    displayName: '勤勉',
    type: 'Equipment',
    category: 'primary',
    tags: ['MarksmanRifle', 'ap2'],
    warbondCode: 'warbond3',
    internalName: 'r63diligence',
    imageURL: 'r63diligence.png',
    antitank: false,
    tier: 'b',
    index: 27,
  },
  {
    displayName: '反狙击勤勉',
    type: 'Equipment',
    category: 'primary',
    tags: ['MarksmanRifle', 'ap3'],
    warbondCode: 'warbond3',
    internalName: 'r63csdiligencecountersniper',
    imageURL: 'r63csdiligencecountersniper.png',
    antitank: false,
    tier: 'b',
    index: 28,
  },
  {
    displayName: '神枪手',
    type: 'Equipment',
    category: 'primary',
    tags: ['MarksmanRifle', 'ap3'],
    warbondCode: 'warbond14',
    internalName: 'r6deadeye',
    imageURL: 'r6deadeye.png',
    antitank: false,
    tier: 'a',
    index: 29,
  },
  {
    displayName: '修正案',
    type: 'Equipment',
    category: 'primary',
    tags: ['MarksmanRifle', 'ap2', 'melee'],
    warbondCode: 'warbond15',
    internalName: 'r2amendment',
    imageURL: 'r2amendment.png',
    antitank: false,
    tier: 'a',
    index: 30,
  },
  {
    displayName: '审查者',
    type: 'Equipment',
    category: 'primary',
    tags: ['MarksmanRifle', 'ap2', 'suppressed'],
    warbondCode: 'warbond22',
    internalName: 'r72censor',
    imageURL: 'r72censor.webp',
    antitank: false,
    tier: 'a',
    index: 31,
  },
  {
    displayName: '宪法',
    type: 'Equipment',
    category: 'primary',
    tags: ['MarksmanRifle', 'ap3', 'melee'],
    warbondCode: 'none',
    internalName: 'r2124constitution',
    imageURL: 'r2124constitution.png',
    antitank: false,
    tier: 'c',
    index: 32,
  },
  {
    displayName: '长柄镰',
    type: 'Equipment',
    category: 'primary',
    tags: ['EnergyWeapon', 'ap2', 'laser'],
    warbondCode: 'warbond3',
    internalName: 'las5scythe',
    imageURL: 'las5scythe.png',
    antitank: false,
    tier: 'b',
    index: 33,
  },
  {
    displayName: '镰刀',
    type: 'Equipment',
    category: 'primary',
    tags: ['EnergyWeapon', 'ap2'],
    warbondCode: 'warbond5',
    internalName: 'las16sickle',
    imageURL: 'las16sickle.png',
    antitank: false,
    tier: 'a',
    index: 34,
  },
  {
    displayName: '焦土',
    type: 'Equipment',
    category: 'primary',
    tags: ['EnergyWeapon', 'ap3', 'plasma'],
    warbondCode: 'warbond3',
    internalName: 'plas1scorcher',
    imageURL: 'plas1scorcher.png',
    antitank: false,
    tier: 's',
    index: 35,
  },
  {
    displayName: '净化者',
    type: 'Equipment',
    category: 'primary',
    tags: ['EnergyWeapon', 'ap3', 'plasma'],
    warbondCode: 'warbond7',
    internalName: 'plas101purifier',
    imageURL: 'plas101purifier.png',
    antitank: false,
    tier: 's',
    index: 36,
  },
  {
    displayName: '等离子制裁者',
    type: 'Equipment',
    category: 'primary',
    tags: ['EnergyWeapon', 'ap3', 'plasma'],
    warbondCode: 'warbond5',
    internalName: 'sg8ppunisherplasma',
    imageURL: 'sg8ppunisherplasma.png',
    antitank: false,
    tier: 's',
    index: 37,
  },
  {
    displayName: '雷霆',
    type: 'Equipment',
    category: 'primary',
    tags: ['EnergyWeapon', 'ap3', 'arc'],
    warbondCode: 'warbond5',
    internalName: 'arc12blitzer',
    imageURL: 'arc12blitzer.png',
    antitank: false,
    tier: 's',
    index: 38,
  },
  {
    displayName: '双刃镰刀',
    type: 'Equipment',
    category: 'primary',
    tags: ['EnergyWeapon', 'ap2', 'ap3', 'ap4'],
    warbondCode: 'warbond13',
    internalName: 'las17doubleedgesickle',
    imageURL: 'las17doubleedgesickle.png',
    antitank: false,
    tier: 'a',
    index: 39,
  },
  {
    displayName: 'PLAS-39 加速步枪',
    type: 'Equipment',
    category: 'primary',
    tags: ['MarksmanRifle', 'ap3', 'plasma'],
    warbondCode: 'warbond18',
    internalName: 'plas39acceleratorrifle',
    imageURL: 'plas39acceleratorrifle.png',
    antitank: false,
    tier: 'b',
    index: 40,
  },
  {
    displayName: '爆裂铳',
    type: 'Equipment',
    category: 'primary',
    tags: ['Explosive', 'ap4', 'explosive'],
    warbondCode: 'warbond6',
    internalName: 'r36eruptor',
    imageURL: 'r36eruptor.png',
    antitank: true,
    tier: 's',
    index: 41,
  },
  {
    displayName: '爆裂弩',
    type: 'Equipment',
    category: 'primary',
    tags: ['Explosive', 'ap3', 'explosive', 'onehanded'],
    warbondCode: 'warbond6',
    internalName: 'cb9explodingcrossbow',
    imageURL: 'cb9explodingcrossbow.png',
    antitank: false,
    tier: 's',
    index: 42,
  },
  {
    displayName: '变量',
    type: 'Equipment',
    category: 'primary',
    tags: ['AssaultRifle', 'ap2'],
    warbondCode: 'warbond17',
    internalName: 'variable',
    imageURL: 'variable.png',
    antitank: false,
    tier: 'b',
    index: 43,
  },
  {
    displayName: '主宰',
    type: 'Equipment',
    category: 'primary',
    tags: ['Explosive', 'ap3'],
    warbondCode: 'warbond4',
    internalName: 'jar5dominator',
    imageURL: 'jar5dominator.png',
    antitank: false,
    tier: 'b',
    index: 44,
  },
  {
    displayName: '火炬手',
    type: 'Equipment',
    category: 'primary',
    tags: ['Special', 'ap4', 'fire'],
    warbondCode: 'warbond9',
    internalName: 'flam66torcher',
    imageURL: 'flam66torcher.png',
    antitank: false,
    tier: 'b',
    index: 45,
  },
  {
    displayName: '三叉戟',
    type: 'Equipment',
    category: 'primary',
    tags: ['EnergyWeapon', 'ap2'],
    warbondCode: 'warbond23',
    internalName: 'las16trident',
    imageURL: 'las16trident.webp',
    antitank: false,
    tier: 'b',
    index: 46,
  },
  {
    displayName: '司炉者',
    type: 'Equipment',
    category: 'primary',
    tags: ['SubmachineGun', 'ap2', 'ap4', 'fire', 'onehanded'],
    warbondCode: 'warbond24',
    internalName: 'smgflam34stoker',
    imageURL: 'smgflam34stoker.webp',
    antitank: false,
    tier: 'b',
    index: 47,
  },
  {
    displayName: '清扫者',
    type: 'Equipment',
    category: 'primary',
    tags: ['Shotgun', 'ap3', 'melee'],
    warbondCode: 'warbond1',
    internalName: 'sg97sweeper',
    imageURL: 'sg97sweeper.webp',
    antitank: false,
    tier: 'a',
    index: 48,
  },
  {
    displayName: '英勇者',
    type: 'Equipment',
    category: 'primary',
    tags: ['SubmachineGun', 'ap3', 'onehanded'],
    warbondCode: 'warbond25',
    internalName: 'smg203gallant',
    imageURL: 'smg203gallant.webp',
    antitank: false,
    tier: 'a',
    index: 49,
  },
];

// s: 7
// a: 18
// b: 22
// c: 1
