const SECONDARIES = [
  {
    displayName: '和事佬',
    type: 'Equipment',
    category: 'secondary',
    tags: ['pistol', 'ap2'],
    warbondCode: 'none',
    internalName: 'p2peacemaker',
    imageURL: 'p2peacemaker.png',
    antitank: false,
    index: 0,
    tier: 'c',
  },
  {
    displayName: '战斧',
    type: 'Equipment',
    category: 'secondary',
    tags: ['melee', 'ap3'],
    warbondCode: 'warbond1',
    internalName: 'cqc5combathatchet',
    imageURL: 'cqc5combathatchet.png',
    antitank: false,
    index: 1,
    tier: 'c',
  },
  {
    displayName: '军刀',
    type: 'Equipment',
    category: 'secondary',
    tags: ['melee', 'ap3'],
    warbondCode: 'warbond15',
    internalName: 'cqc2saber',
    imageURL: 'cqc2saber.png',
    antitank: false,
    index: 2,
    tier: 'c',
  },
  {
    displayName: '砍刀',
    type: 'Equipment',
    category: 'secondary',
    tags: ['melee', 'ap3'],
    warbondCode: 'warbond1',
    internalName: 'cqc42machete',
    imageURL: 'cqc42machete.png',
    antitank: false,
    index: 3,
    tier: 'c',
  },
  {
    displayName: '眩晕长矛',
    type: 'Equipment',
    category: 'secondary',
    tags: ['melee', 'ap3', 'stun'],
    warbondCode: 'warbond12',
    internalName: 'cqc19stunlance',
    imageURL: 'cqc19stunlance.png',
    antitank: false,
    index: 4,
    tier: 'c',
  },
  {
    displayName: '眩晕警棍',
    type: 'Equipment',
    category: 'secondary',
    tags: ['melee', 'ap3', 'stun'],
    warbondCode: 'warbond1',
    internalName: 'cqc30stunbaton',
    imageURL: 'cqc30stunbaton.png',
    antitank: false,
    index: 5,
    tier: 'c',
  },
  {
    displayName: '救世主',
    type: 'Equipment',
    category: 'secondary',
    tags: ['pistol', 'ap2'],
    warbondCode: 'warbond3',
    internalName: 'p19redeemer',
    imageURL: 'p19redeemer.png',
    antitank: false,
    index: 6,
    tier: 'b',
  },
  {
    displayName: '裁决',
    type: 'Equipment',
    category: 'secondary',
    tags: ['pistol', 'ap3'],
    warbondCode: 'warbond7',
    internalName: 'p113verdict',
    imageURL: 'p113verdict.png',
    antitank: false,
    index: 7,
    tier: 'b',
  },
  {
    displayName: '参议员',
    type: 'Equipment',
    category: 'secondary',
    tags: ['pistol', 'ap4'],
    warbondCode: 'warbond4',
    internalName: 'p4senator',
    imageURL: 'p4senator.png',
    antitank: false,
    index: 8,
    tier: 'a',
  },
  {
    displayName: 'P-92 授权令',
    type: 'Equipment',
    category: 'secondary',
    tags: ['pistol', 'ap3', 'guided'],
    warbondCode: 'warbond1',
    internalName: 'p92warrant',
    imageURL: 'p92warrant.png',
    antitank: false,
    index: 9,
    tier: 'b',
  },
  {
    displayName: 'M6C/SOCOM',
    type: 'Equipment',
    category: 'secondary',
    tags: ['pistol', 'ap2', 'suppressed'],
    warbondCode: 'warbond19',
    internalName: 'm6csocompistol',
    imageURL: 'm6csocompistol.png',
    antitank: false,
    index: 10,
    tier: 'b',
  },
  {
    displayName: '兴奋剂手枪',
    type: 'Equipment',
    category: 'secondary',
    tags: ['Special'],
    warbondCode: 'warbond10',
    internalName: 'p11stimpistol',
    imageURL: 'p11stimpistol.png',
    antitank: false,
    index: 11,
    tier: 'b',
  },
  {
    displayName: '忠诚者',
    type: 'Equipment',
    category: 'secondary',
    tags: ['plasma', 'ap3'],
    warbondCode: 'warbond11',
    internalName: 'plas15loyalist',
    imageURL: 'plas15loyalist.png',
    antitank: false,
    index: 12,
    tier: 'a',
  },
  {
    displayName: '游击兵手喷',
    type: 'Equipment',
    category: 'secondary',
    tags: ['ap2'],
    warbondCode: 'warbond8',
    internalName: 'sg22bushwhacker',
    imageURL: 'sg22bushwhacker.png',
    antitank: false,
    index: 13,
    tier: 'b',
  },
  {
    displayName: '榴弹手枪',
    type: 'Equipment',
    category: 'secondary',
    tags: ['explosive', 'ap3'],
    warbondCode: 'warbond6',
    internalName: 'gp31grenadepistol',
    imageURL: 'gp31grenadepistol.png',
    antitank: false,
    index: 14,
    tier: 'a',
  },
  {
    displayName: '再教育者',
    type: 'Equipment',
    category: 'secondary',
    tags: ['gas', 'ap4'],
    warbondCode: 'warbond22',
    internalName: 'p35reeducator',
    imageURL: 'p35reeducator.webp',
    antitank: false,
    index: 15,
    tier: 'c',
  },
  {
    displayName: '匕首',
    type: 'Equipment',
    category: 'secondary',
    tags: ['laser', 'ap2'],
    warbondCode: 'warbond5',
    internalName: 'las7dagger',
    imageURL: 'las7dagger.png',
    antitank: false,
    index: 16,
    tier: 'c',
  },
  {
    displayName: '利爪',
    type: 'Equipment',
    category: 'secondary',
    tags: ['ap3'],
    warbondCode: 'warbond14',
    internalName: 'las58talon',
    imageURL: 'las58talon.png',
    antitank: false,
    index: 17,
    tier: 'a',
  },
  {
    displayName: '脆烤者',
    type: 'Equipment',
    category: 'secondary',
    tags: ['fire', 'ap4'],
    warbondCode: 'warbond9',
    internalName: 'p72crisper',
    imageURL: 'p72crisper.png',
    antitank: false,
    index: 18,
    tier: 'b',
  },
  {
    displayName: 'GP-31 最后通牒',
    type: 'Equipment',
    category: 'secondary',
    tags: ['explosive', 'at'],
    warbondCode: 'warbond13',
    internalName: 'gp31ultimatum',
    imageURL: 'gp31ultimatum.png',
    antitank: true,
    index: 19,
    tier: 's',
  },
  {
    displayName: '否决',
    type: 'Equipment',
    category: 'secondary',
    tags: ['pistol', 'ap3'],
    warbondCode: 'warbond24',
    internalName: 'p69veto',
    imageURL: 'p69veto.webp',
    antitank: false,
    index: 20,
    tier: 'b',
  },
  {
    displayName: '壕沟工具',
    type: 'Equipment',
    category: 'secondary',
    tags: ['melee', 'ap3'],
    warbondCode: 'warbond24',
    internalName: 'cqc73entrenchmenttool',
    imageURL: 'cqc73entrenchmenttool.webp',
    antitank: false,
    index: 21,
    tier: 'c',
  },
  {
    displayName: '导弹手枪',
    type: 'Equipment',
    category: 'secondary',
    tags: ['explosive', 'at', 'guided'],
    warbondCode: 'warbond25',
    internalName: 'p33missilepistol',
    imageURL: 'p33missilepistol.webp',
    antitank: true,
    index: 22,
    tier: 'a',
  },
];

// s: 2
// a: 4
// b: 6
// c: 6
