const SPECIALISTS = [
  {
    displayName: '狂热殉道者',
    starterItems: ['Portable Hellbomb', 'Combat Hatchet', 'Integrated Explosives armor'],
    stratagems: ['Portable Hellbomb'],
    primaries: [],
    boosters: [],
    secondaries: ['Combat Hatchet'],
    throwables: [],
    armorPassives: ['Integrated Explosives'],
    traits: [],
    imageURL: 'zealousMartyr.png',
    warbonds: ['warbond1', 'warbond13'],
  },
  {
    displayName: '永久治疗代表',
    starterItems: ['Stim Pistol', 'Med-Kit armor'],
    stratagems: [],
    primaries: [],
    boosters: [],
    secondaries: ['Stim Pistol'],
    throwables: [],
    armorPassives: ['Med-Kit'],
    traits: [],
    imageURL: 'permacuraRep.png',
    warbonds: ['warbond10'],
  },
  {
    displayName: '旗手',
    starterItems: ['One True Flag', 'Reinforced Epaulettes armor', 'Stamina Enhancement booster'],
    stratagems: ['One True Flag'],
    primaries: [],
    boosters: ['Stamina Enhancement'],
    secondaries: [],
    throwables: [],
    armorPassives: ['Reinforced Epaulettes'],
    traits: [],
    imageURL: 'theFlagBearer.png',
    warbonds: ['warbond15'],
  },
  {
    displayName: '速通者',
    starterItems: ['Fast Recon Vehicle', 'Expert Extraction Pilot booster or Dead Sprint booster'],
    stratagems: ['Fast Recon Vehicle'],
    primaries: [],
    boosters: ['Expert Extraction Pilot', 'Dead Sprint'],
    secondaries: [],
    throwables: [],
    armorPassives: ['Oxygenator'],
    traits: [],
    imageURL: '',
    warbonds: [],
  },
  {
    displayName: '毒蛇突击兵',
    starterItems: ['Liberator Carbine', 'Peak Physique armor', 'Throwing Knives'],
    stratagems: [],
    primaries: ['Liberator Carbine'],
    boosters: [],
    secondaries: [],
    throwables: ['K-2 Throwing Knife'],
    armorPassives: ['Peak Physique'],
    traits: [],
    imageURL: 'viperCommando.png',
    warbonds: ['warbond8'],
  },
  {
    displayName: '纵火狂',
    starterItems: ['Torcher', 'Crisper', 'Inflammable armor'],
    stratagems: [],
    primaries: ['Torcher'],
    boosters: [],
    secondaries: ['Crisper'],
    throwables: [],
    armorPassives: ['Inflammable'],
    traits: [],
    imageURL: 'pyromaniac.webp',
    warbonds: ['warbond9'],
  },
  {
    displayName: '闪电虫',
    starterItems: ['Arc Thrower', 'Tesla Tower', 'Electrical Conduit armor'],
    stratagems: ['Arc Thrower', 'Tesla Tower'],
    primaries: [],
    boosters: [],
    secondaries: [],
    throwables: [],
    armorPassives: ['Electrical Conduit'],
    traits: [],
    imageURL: 'lightningBug.webp',
    warbonds: ['warbond5'],
  },
  {
    displayName: '侦察狙击手',
    starterItems: ['Diligence', 'UAV Recon booster', 'Scout armor'],
    stratagems: [],
    primaries: ['Diligence'],
    boosters: ['UAV Recon'],
    secondaries: [],
    throwables: [],
    armorPassives: ['Scout'],
    traits: [],
    imageURL: 'scoutSniper.webp',
    warbonds: [],
  },
  {
    displayName: '真理执行者',
    starterItems: ['Reprimand or Halt', 'Unflinching armor'],
    stratagems: [],
    primaries: ['Reprimand', 'Halt'],
    boosters: [],
    secondaries: [],
    throwables: [],
    armorPassives: ['Unflinching'],
    traits: [],
    imageURL: 'truthEnforcer.webp',
    warbonds: ['warbond11'],
  },
  {
    displayName: '灭虫者',
    starterItems: ['Gas grenades', 'Sterilizer', 'Advanced Filtration armor'],
    stratagems: ['Sterilizer'],
    primaries: [],
    boosters: [],
    secondaries: [],
    throwables: ['G-4 Gas'],
    armorPassives: ['Advanced Filtration'],
    traits: [],
    imageURL: 'exterminator.webp',
    warbonds: ['warbond10'],
  },
  {
    displayName: '突击兵',
    starterItems: [
      'StA-52 Assault Rifle, PLAS-39 Accelerator Rifle, or StA-11 SMG',
      'Acclimated armor',
    ],
    stratagems: [],
    primaries: ['StA-52 Assault Rifle', 'PLAS-39 Accelerator Rifle', 'StA-11 SMG'],
    boosters: [],
    secondaries: [],
    throwables: [],
    armorPassives: ['Acclimated'],
    traits: [],
    imageURL: 'assaultTrooper.webp',
    warbonds: ['warbond18'],
  },
  {
    displayName: '战利品地精',
    starterItems: ['Supply Pack', 'Sample Scanner booster'],
    stratagems: ['Supply Pack'],
    primaries: [],
    boosters: ['Sample Scanner'],
    secondaries: [],
    throwables: [],
    armorPassives: [],
    traits: [],
    imageURL: 'lootGoblin.webp',
    warbonds: ['warbond15'],
  },
  {
    displayName: '逃脱大师',
    starterItems: ['Jump Pack', 'Smoke Grenades'],
    stratagems: ['Jump Pack'],
    primaries: [],
    boosters: [],
    secondaries: [],
    throwables: ['G-3 Smoke'],
    armorPassives: [],
    traits: [],
    imageURL: 'escapeArtist.webp',
    warbonds: [],
  },
  {
    displayName: '仲裁者',
    starterItems: ['P-92 Warrant', 'Ballistic Shield', 'Ballistic Padding armor'],
    stratagems: ['Ballistic Shield'],
    primaries: [],
    boosters: [],
    secondaries: ['P-92 Warrant'],
    throwables: [],
    armorPassives: ['Ballistic Padding'],
    traits: [],
    imageURL: 'arbiter.webp',
    warbonds: ['warbond1', 'warbond16'],
  },
  {
    displayName: '实验体 #4311',
    starterItems: ['Warp Pack', 'Adreno-Defibrillator armor'],
    stratagems: ['Warp Pack'],
    primaries: [],
    boosters: [],
    secondaries: [],
    throwables: [],
    armorPassives: ['Adreno-Defibrillator'],
    traits: [],
    imageURL: 'testSubject4311.png',
    warbonds: ['warbond17'],
  },
  {
    displayName: '城市士兵',
    starterItems: ['Defender', 'Siege Ready armor'],
    stratagems: [],
    primaries: ['Defender'],
    boosters: [],
    secondaries: [],
    throwables: [],
    armorPassives: ['Siege Ready'],
    traits: [],
    imageURL: 'urbanSoldier.webp',
    warbonds: ['warbond12'],
  },
  {
    displayName: '传教士',
    starterItems: ['Senator or Talon', 'Gunslinger armor'],
    stratagems: [],
    primaries: [],
    boosters: [],
    secondaries: ['Senator', 'Talon'],
    throwables: [],
    armorPassives: ['Gunslinger'],
    traits: ['无法随机获得支援武器'],
    imageURL: 'preacher.webp',
    warbonds: ['warbond14'],
  },
  {
    displayName: '地狱舱爱好者',
    starterItems: ['Expendable Anti-Tank', 'Firebomb Hellpods booster'],
    stratagems: ['Expendable Anti-Tank'],
    primaries: [],
    boosters: ['Firebomb Hellpods', 'Stun Pods', 'Concealed Insertion'],
    secondaries: [],
    throwables: [],
    armorPassives: [],
    traits: ['无法随机获得飞鹰或轨道战备'],
    imageURL: 'hellpodEnthusiast.webp',
    warbonds: ['warbond9'],
  },
  {
    displayName: '轨道空降兵',
    starterItems: ['MA5C Assault Rifle', 'M7S SMG', 'or M90A Shotgun', 'Feet First armor'],
    stratagems: [],
    primaries: ['MA5C Assault Rifle', 'M7S SMG', 'M90A Shotgun'],
    boosters: [],
    secondaries: [],
    throwables: [],
    armorPassives: ['Feet First'],
    traits: [],
    imageURL: 'theOdst.webp',
    warbonds: ['warbond19'],
  },
  {
    displayName: '萨多卡',
    starterItems: ['Shield Generator Pack', 'Desert Stormer armor', 'Machete or Saber'],
    stratagems: ['Shield Generator Pack'],
    primaries: [],
    boosters: [],
    secondaries: ['Machete', 'Saber'],
    throwables: [],
    armorPassives: ['Desert Stormer'],
    traits: [],
    imageURL: 'sardaukar.webp',
    warbonds: ['warbond20', 'warbond15'],
  },
  {
    displayName: '蟒蛇突击兵',
    starterItems: ['Rock Solid armor', 'Maxigun'],
    stratagems: ['Maxigun'],
    primaries: [],
    boosters: [],
    secondaries: [],
    throwables: [],
    armorPassives: ['Rock Solid'],
    traits: [],
    imageURL: 'pythoncommando.webp',
    warbonds: ['warbond21'],
  },
  {
    displayName: '毁灭战士',
    starterItems: ['Rock Solid armor', 'Double Freedom'],
    stratagems: [],
    primaries: ['Double Freedom'],
    boosters: [],
    secondaries: [],
    throwables: [],
    armorPassives: ['Rock Solid'],
    traits: [],
    imageURL: 'doomguy.webp',
    warbonds: ['warbond21', 'warbond1'],
  },
  {
    displayName: '军犬训导员',
    starterItems: [
      'Guard Dog Bullets',
      'Guard Dog Laser',
      'Guard Dog Breath',
      'Guard Dog Arc',
      'and/or Guard Dog Flames',
    ],
    stratagems: [
      'Guard Dog Bullets',
      'Guard Dog Laser',
      'Guard Dog Breath',
      'Guard Dog Arc',
      'Guard Dog Flames',
    ],
    primaries: [],
    boosters: [],
    secondaries: [],
    throwables: [],
    armorPassives: [],
    traits: ['无法随机获得战备'],
    imageURL: 'k9handler.webp',
    warbonds: ['warbond21', 'warbond10', 'warbond16'],
  },
  {
    displayName: '破坏者',
    starterItems: ['C4 Pack', 'Reduced Signature armor', 'Concealed Insertion booster'],
    stratagems: ['C4 Pack'],
    primaries: [],
    boosters: ['Concealed Insertion'],
    secondaries: [],
    throwables: [],
    armorPassives: ['Reduced Signature'],
    traits: [],
    imageURL: 'saboteur.webp',
    warbonds: ['warbond22'],
  },
  {
    displayName: '刺客',
    starterItems: ['Censor or Suppressor', 'Reduced Signature armor'],
    stratagems: [],
    primaries: ['Censor', 'Suppressor'],
    boosters: [],
    secondaries: [],
    throwables: [],
    armorPassives: ['Reduced Signature'],
    traits: [],
    imageURL: 'assassin.webp',
    warbonds: ['warbond22'],
  },
  {
    displayName: '破城者',
    starterItems: ['Leveller', 'Supplementary Adrenaline armor'],
    stratagems: ['Leveller'],
    primaries: [],
    boosters: [],
    secondaries: [],
    throwables: [],
    armorPassives: ['Supplementary Adrenaline'],
    traits: [],
    imageURL: 'siegebreaker.png',
    warbonds: ['warbond23'],
  },
  {
    displayName: '主宰者',
    starterItems: ['Breaching Hammer', 'Shield Generator Pack', 'Supplementary Adrenaline armor'],
    stratagems: ['Breaching Hammer', 'Shield Generator Pack'],
    primaries: [],
    boosters: [],
    secondaries: [],
    throwables: [],
    armorPassives: ['Supplementary Adrenaline'],
    traits: [],
    imageURL: 'juggernaut.png',
    warbonds: ['warbond23'],
  },
  {
    displayName: '克里格士兵',
    starterItems: ['Entrenchment Tool', 'Concussive Padding armor', 'Orbital Gas Strike'],
    stratagems: ['Orbital Gas Strike'],
    primaries: [],
    boosters: [],
    secondaries: ['Entrenchment Tool'],
    throwables: [],
    armorPassives: ['Concussive Padding'],
    traits: [],
    imageURL: '',
    warbonds: ['warbond24'],
  },
  {
    displayName: '指挥官',
    starterItems: ['Veto', 'Concussive Padding armor', 'Orbital Railcannon Strike'],
    stratagems: ['Orbital Railcannon Strike'],
    primaries: [],
    boosters: [],
    secondaries: ['Veto'],
    throwables: [],
    armorPassives: ['Concussive Padding'],
    traits: [],
    imageURL: '',
    warbonds: ['warbond24'],
  },
  {
    displayName: '突击陆战队员',
    starterItems: ['Jump Pack', 'Defoliation Tool and/or Breaching Hammer'],
    stratagems: ['Jump Pack', 'Defoliation Tool', 'Breaching Hammer'],
    primaries: [],
    boosters: [],
    secondaries: [],
    throwables: [],
    armorPassives: [],
    traits: [],
    imageURL: '',
    warbonds: ['warbond23', 'warbond21'],
  },
  {
    displayName: '飞鹰地面协调员',
    starterItems: ['Servo-Assisted armor', 'Eagle Strafing Run'],
    stratagems: ['Eagle Strafing Run'],
    primaries: [],
    boosters: [],
    secondaries: [],
    throwables: [],
    armorPassives: ['Servo-Assisted'],
    traits: ['只能随机获得飞鹰战备'],
    imageURL: 'egc.webp',
    warbonds: [],
  },
  {
    displayName: '轨道轰炸地面协调员',
    starterItems: ['Servo-Assisted armor', 'Orbital Precision Strike'],
    stratagems: ['Orbital Precision Strike'],
    primaries: [],
    boosters: [],
    secondaries: [],
    throwables: [],
    armorPassives: ['Servo-Assisted'],
    traits: ['只能随机获得轨道战备'],
    imageURL: 'ogc.webp',
    warbonds: [],
  },
  {
    displayName: '扫雷兵',
    starterItems: ['Lure Mines', 'Anti-Personnel Mines'],
    stratagems: ['Anti-Personnel Mines'],
    primaries: [],
    boosters: [],
    secondaries: [],
    throwables: ['TM-01 Lure Mine'],
    armorPassives: [],
    traits: ['只能随机获得地雷战备'],
    imageURL: '',
    warbonds: [],
  },
  {
    displayName: '战斗工程师',
    starterItems: ['Pummeler', 'Machine Gun Sentry', 'Engineering Kit armor'],
    stratagems: ['Machine Gun Sentry'],
    primaries: ['Pummeler'],
    boosters: [],
    secondaries: [],
    throwables: [],
    armorPassives: ['Engineering Kit'],
    traits: ['只能随机获得哨塔战备'],
    imageURL: '',
    warbonds: [],
  },
  {
    displayName: '执法者',
    starterItems: ['De-Escalator', 'Ballistic Padding armor', 'Stun Pods'],
    stratagems: ['De-Escalator'],
    primaries: [],
    boosters: ['Stun Pods'],
    secondaries: [],
    throwables: [],
    armorPassives: ['Ballistic Padding'],
    traits: [],
    imageURL: '',
    warbonds: [],
  },
  {
    displayName: '激光兵',
    starterItems: ['Scythe', 'Guard Dog Laser'],
    stratagems: ['Guard Dog Laser'],
    primaries: ['Scythe'],
    boosters: [],
    secondaries: [],
    throwables: [],
    armorPassives: [],
    traits: [],
    imageURL: '',
    warbonds: [],
  },
  {
    displayName: 'L.A.N.C.E.',
    starterItems: ['Anti-Material Rifle', 'Hover Pack'],
    stratagems: ['Hover Pack', 'Anti-Material Rifle'],
    primaries: [],
    boosters: [],
    secondaries: [],
    throwables: [],
    armorPassives: [],
    traits: [],
    imageURL: '',
    warbonds: [],
  },
  {
    displayName: '乌龟',
    starterItems: ['Shield Generator Pack', 'G/SH-39 Shield'],
    stratagems: ['Shield Generator Pack'],
    primaries: [],
    boosters: [],
    secondaries: [],
    throwables: ['G/SH-39 Shield'],
    armorPassives: [],
    traits: [],
    imageURL: '',
    warbonds: [],
  },
  {
    displayName: '飞行员',
    starterItems: ['Breakthrough Exosuit', 'Oxygenator armor'],
    stratagems: ['Breakthrough Exosuit'],
    primaries: [],
    boosters: [],
    secondaries: [],
    throwables: [],
    armorPassives: ['Oxygenator'],
    traits: ['只能随机获得载具、外骨骼和飞鹰战备'],
    imageURL: '',
    warbonds: [],
  },
  {
    displayName: '危险分子',
    starterItems: ['Airburst Rocket Launcher', 'G-7 Pineapple'],
    stratagems: ['Airburst Rocket Launcher'],
    primaries: [],
    boosters: [],
    secondaries: [],
    throwables: ['G-7 Pineapple'],
    armorPassives: [],
    traits: [],
    imageURL: '',
    warbonds: [],
  },
  {
    displayName: '坦克猎手',
    starterItems: ['Anti-Tank Emplacement', 'G-123 Thermite'],
    stratagems: ['Anti-Tank Emplacement'],
    primaries: [],
    boosters: [],
    secondaries: [],
    throwables: ['G-123 Thermite'],
    armorPassives: [],
    traits: ['只能随机获得反坦克战备'],
    imageURL: '',
    warbonds: [],
  },
  {
    displayName: '渔夫',
    starterItems: ['Speargun'],
    stratagems: ['Speargun'],
    primaries: [],
    boosters: [],
    secondaries: [],
    throwables: [],
    armorPassives: [],
    traits: [],
    imageURL: '',
    warbonds: [],
  },
  {
    displayName: '斯巴达',
    starterItems: ['Ballistic Shield', 'Peak Physique armor', 'Melee weapon secondaries'],
    stratagems: ['Ballistic Shield'],
    primaries: [],
    boosters: [],
    secondaries: ['Stun Lance', 'Stun Baton', 'Machete', 'Saber', 'Combat Hatchet'],
    throwables: [],
    armorPassives: ['Peak Physique'],
    traits: [],
    imageURL: '',
    warbonds: [],
  },
  {
    displayName: '阿诺德',
    starterItems: ['Commando', 'Dynamite', 'Verdict'],
    stratagems: ['Commando'],
    primaries: [],
    boosters: [],
    secondaries: ['Verdict'],
    throwables: ['Dynamite'],
    armorPassives: [],
    traits: [],
    imageURL: '',
    warbonds: [],
  },
  {
    displayName: '消耗品',
    starterItems: ['Bullet Storm'],
    stratagems: ['Bullet Storm'],
    primaries: [],
    boosters: [],
    secondaries: [],
    throwables: [],
    armorPassives: [],
    traits: ['只能随机获得消耗型战备'],
    imageURL: '',
    warbonds: [],
  },
];
