// tags: ap2, ap3, ap4, gas, smoke, expendable, fire, at, bullets, laser, arc, stun, explosive, plasma, melee Weapons, movement, Backpacks, Vehicles, Sentry, Emplacement, Eagle, Orbital
const STRATAGEMS = [
  {
    displayName: '灭菌者',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons', 'gas', 'ap4'],
    warbondCode: 'warbond10',
    internalName: 'tx41sterilizer',
    imageURL: 'tx41sterilizer.svg',
    antitank: false,
    tier: 'c',
    index: 0,
  },
  {
    displayName: '火焰喷射器',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons', 'fire', 'ap4'],
    warbondCode: 'none',
    internalName: 'flam40flamethrower',
    imageURL: 'flam40flamethrower.svg',
    antitank: false,
    tier: 'b',
    index: 1,
  },
  {
    displayName: 'S-11矛枪',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons', 'gas', 'ap4'],
    warbondCode: 'warbond20',
    internalName: 'speargun',
    imageURL: 'speargun.svg',
    antitank: false,
    tier: 'a',
    index: 2,
  },
  {
    displayName: '激光大炮',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons', 'laser', 'ap4'],
    warbondCode: 'none',
    internalName: 'las98lasercannon',
    imageURL: 'las98lasercannon.svg',
    antitank: true,
    tier: 'b',
    index: 3,
  },
  {
    displayName: '盟友',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons', 'bullets', 'ap2'],
    warbondCode: 'none',
    internalName: 'm105stalwart',
    imageURL: 'm105stalwart.svg',
    antitank: false,
    tier: 'a',
    index: 4,
  },
  {
    displayName: '机枪',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons', 'bullets', 'ap3'],
    warbondCode: 'none',
    internalName: 'mg43machinegun',
    imageURL: 'mg43machinegun.svg',
    antitank: false,
    tier: 'b',
    index: 5,
  },
  {
    displayName: '重机枪',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons', 'bullets', 'ap4'],
    warbondCode: 'none',
    internalName: 'mg206heavymachinegun',
    imageURL: 'mg206heavymachinegun.svg',
    antitank: true,
    tier: 'b',
    index: 6,
  },
  {
    displayName: '电弧发射器',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons', 'arc'],
    warbondCode: 'none',
    internalName: 'arc3arcthrower',
    imageURL: 'arc3arcthrower.svg',
    antitank: false,
    tier: 'b',
    index: 7,
  },
  {
    displayName: '榴弹发射器',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons', 'explosive', 'ap3'],
    warbondCode: 'none',
    internalName: 'gl21grenadelauncher',
    imageURL: 'gl21grenadelauncher.svg',
    antitank: false,
    tier: 'a',
    index: 8,
  },
  {
    displayName: 'GL-52 缓和使者',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons', 'arc'],
    warbondCode: 'warbond16',
    internalName: 'gl52deescalator',
    imageURL: 'gl52deescalator.svg',
    antitank: true,
    tier: 'a',
    index: 9,
  },
  {
    displayName: '反器材步枪',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons', 'bullets', 'ap4'],
    warbondCode: 'none',
    internalName: 'apw1antimaterielrifle',
    imageURL: 'apw1antimaterielrifle.svg',
    antitank: true,
    tier: 'a',
    index: 10,
  },
  {
    displayName: '磁轨炮',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons', 'at'],
    warbondCode: 'none',
    internalName: 'rs422railgun',
    imageURL: 'rs422railgun.svg',
    antitank: true,
    tier: 'b',
    index: 11,
  },
  {
    displayName: '类星体大炮',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons', 'at'],
    warbondCode: 'none',
    internalName: 'las99quasarcannon',
    imageURL: 'las99quasarcannon.svg',
    antitank: true,
    tier: 's',
    index: 12,
  },
  {
    displayName: 'PLAS-45 纪元',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons', 'plasma', 'at'],
    warbondCode: 'warbond17',
    internalName: 'epoch',
    imageURL: 'epoch.svg',
    antitank: true,
    tier: 'a',
    index: 13,
  },
  {
    displayName: '反坦克消耗品',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons', 'expendable', 'at'],
    warbondCode: 'none',
    internalName: 'eat17expendableantitank',
    imageURL: 'eat17expendableantitank.svg',
    antitank: true,
    tier: 'a',
    index: 14,
  },
  {
    displayName: '突击兵',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons', 'expendable', 'at'],
    warbondCode: 'none',
    internalName: 'mls4xcommandorocketlauncher',
    imageURL: 'mls4xcommandorocketlauncher.svg',
    antitank: true,
    tier: 'a',
    index: 15,
  },
  {
    displayName: '消耗型凝固汽油弹',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons', 'expendable', 'fire'],
    warbondCode: 'warbond20',
    internalName: 'eat700expendablenapalm',
    imageURL: 'eat700expendablenapalm.svg',
    antitank: false,
    tier: 'b',
    index: 16,
  },
  {
    displayName: '单发导弹筒',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons', 'expendable', 'at'],
    warbondCode: 'warbond20',
    internalName: 'solosilo',
    imageURL: 'solosilo.svg',
    antitank: true,
    tier: 'a',
    index: 17,
  },
  {
    displayName: '唯一真旗',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons', 'melee'],
    warbondCode: 'warbond15',
    internalName: 'onetrueflag',
    imageURL: 'onetrueflag.svg',
    antitank: false,
    tier: 'c',
    index: 18,
  },
  {
    displayName: '除草器',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons', 'melee'],
    warbondCode: 'warbond21',
    internalName: 'defoliationtool',
    imageURL: 'defoliationtool.svg',
    antitank: false,
    tier: 'c',
    index: 19,
  },
  {
    displayName: '麦西极枪',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons', 'Backpacks', 'bullets', 'ap3'],
    warbondCode: 'warbond21',
    internalName: 'maxigun',
    imageURL: 'maxigun.svg',
    antitank: false,
    tier: 'a',
    index: 20,
  },
  {
    displayName: '机炮',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons', 'Backpacks', 'explosive'],
    warbondCode: 'none',
    internalName: 'ac8autocannon',
    imageURL: 'ac8autocannon.svg',
    antitank: true,
    tier: 'a',
    index: 21,
  },
  {
    displayName: 'StA-X3 W.A.S.P. 火箭发射器',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons', 'Backpacks', 'explosive'],
    warbondCode: 'none',
    internalName: 'wasplauncher',
    imageURL: 'wasplauncher.svg',
    antitank: true,
    tier: 'a',
    index: 22,
  },
  {
    displayName: '空爆火箭发射器',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons', 'Backpacks', 'explosive'],
    warbondCode: 'none',
    internalName: 'rl77airburstrocketlauncher',
    imageURL: 'rl77airburstrocketlauncher.svg',
    antitank: false,
    tier: 'b',
    index: 23,
  },
  {
    displayName: '无后坐力炮',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons', 'Backpacks', 'explosive', 'at'],
    warbondCode: 'none',
    internalName: 'gr8recoillessrifle',
    imageURL: 'gr8recoillessrifle.svg',
    antitank: true,
    tier: 's',
    index: 24,
  },
  {
    displayName: '长矛导弹',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons', 'Backpacks', 'explosive', 'at'],
    warbondCode: 'none',
    internalName: 'faf14spear',
    imageURL: 'faf14spear.svg',
    antitank: true,
    tier: 'b',
    index: 25,
  },
  {
    displayName: 'C4 背包',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons', 'Backpacks', 'explosive', 'at'],
    warbondCode: 'warbond22',
    internalName: 'c4pack',
    imageURL: 'c4pack.svg',
    antitank: true,
    tier: 'b',
    index: 26,
  },
  {
    displayName: '护卫犬热狗',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Backpacks', 'fire'],
    warbondCode: 'warbond21',
    internalName: 'guarddogflames',
    imageURL: 'guarddogflames.svg',
    antitank: false,
    tier: 'b',
    index: 27,
  },
  {
    displayName: '护卫犬腐气',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Backpacks', 'gas'],
    warbondCode: 'warbond10',
    internalName: 'axtx13guarddogdogbreath',
    imageURL: 'axtx13guarddogdogbreath.svg',
    antitank: false,
    tier: 'a',
    index: 28,
  },
  {
    displayName: '护卫犬激光',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Backpacks', 'laser', 'ap2'],
    warbondCode: 'none',
    internalName: 'axlas5guarddogrover',
    imageURL: 'axlas5guarddogrover.svg',
    antitank: false,
    tier: 'b',
    index: 29,
  },
  {
    displayName: '护卫犬',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Backpacks', 'bullets', 'ap3'],
    warbondCode: 'none',
    internalName: 'ad334guarddog',
    imageURL: 'ad334guarddog.svg',
    antitank: false,
    tier: 'a',
    index: 30,
  },
  {
    displayName: '护卫犬 K9',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Backpacks', 'arc'],
    warbondCode: 'warbond16',
    internalName: 'guarddogarc',
    imageURL: 'guarddogarc.svg',
    antitank: false,
    tier: 'a',
    index: 31,
  },
  {
    displayName: '跳跃背包',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Backpacks', 'movement'],
    warbondCode: 'none',
    internalName: 'lift850jumppack',
    imageURL: 'lift850jumppack.svg',
    antitank: false,
    tier: 's',
    index: 32,
  },
  {
    displayName: '悬浮背包',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Backpacks', 'movement'],
    warbondCode: 'warbond14',
    internalName: 'lift860hoverpack',
    imageURL: 'lift860hoverpack.svg',
    antitank: false,
    tier: 'b',
    index: 33,
  },
  {
    displayName: '传送背包',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Backpacks', 'movement'],
    warbondCode: 'warbond17',
    internalName: 'warppack',
    imageURL: 'warppack.svg',
    antitank: false,
    tier: 's',
    index: 34,
  },
  {
    displayName: '补给背包',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Backpacks'],
    warbondCode: 'none',
    internalName: 'b1supplypack',
    imageURL: 'b1supplypack.svg',
    antitank: false,
    tier: 's',
    index: 35,
  },
  {
    displayName: '定向护盾',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Backpacks'],
    warbondCode: 'warbond12',
    internalName: 'sh51directionalshield',
    imageURL: 'sh51directionalshield.svg',
    antitank: false,
    tier: 'c',
    index: 36,
  },
  {
    displayName: '防护罩生成背包',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Backpacks'],
    warbondCode: 'none',
    internalName: 'sh20shieldgeneratorpack',
    imageURL: 'sh20shieldgeneratorpack.svg',
    antitank: false,
    tier: 'a',
    index: 37,
  },
  {
    displayName: '弹道防护罩背包',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Backpacks'],
    warbondCode: 'none',
    internalName: 'sh20ballisticshieldbackpack',
    imageURL: 'sh20ballisticshieldbackpack.svg',
    antitank: false,
    tier: 'b',
    index: 38,
  },
  {
    displayName: '可携式绝地弹',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Backpacks', 'at', 'explosive'],
    warbondCode: 'warbond13',
    internalName: 'portablehellbomb',
    imageURL: 'portablehellbomb.svg',
    antitank: true,
    tier: 'a',
    index: 39,
  },
  {
    displayName: '快速侦察载具',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Vehicles', 'movement'],
    warbondCode: 'none',
    internalName: 'fastreconvehicle',
    imageURL: 'fastreconvehicle.svg',
    antitank: false,
    tier: 'a',
    index: 40,
  },
  {
    displayName: '爱国者外骨骼装甲',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Vehicles', 'at', 'exosuit', 'expendable'],
    warbondCode: 'none',
    internalName: 'exo45patriotexosuit',
    imageURL: 'exo45patriotexosuit.svg',
    antitank: true,
    tier: 's',
    index: 41,
  },
  {
    displayName: '解放者外骨骼装甲',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Vehicles', 'at', 'exosuit', 'expendable'],
    warbondCode: 'none',
    internalName: 'exo49emancipatorexosuit',
    imageURL: 'exo49emancipatorexosuit.svg',
    antitank: true,
    tier: 's',
    index: 42,
  },
  {
    displayName: '飞鹰机枪扫射',
    type: 'Stratagem',
    category: 'Eagle',
    tags: ['Eagle'],
    warbondCode: 'none',
    internalName: 'eaglestrafingrun',
    imageURL: 'eaglestrafingrun.svg',
    antitank: false,
    tier: 's',
    index: 43,
  },
  {
    displayName: '飞鹰空袭',
    type: 'Stratagem',
    category: 'Eagle',
    tags: ['Eagle'],
    warbondCode: 'none',
    internalName: 'eagleairstrike',
    imageURL: 'eagleairstrike.svg',
    antitank: true,
    tier: 's',
    index: 44,
  },
  {
    displayName: '飞鹰集束炸弹',
    type: 'Stratagem',
    category: 'Eagle',
    tags: ['Eagle'],
    warbondCode: 'none',
    internalName: 'eagleclusterbomb',
    imageURL: 'eagleclusterbomb.svg',
    antitank: false,
    tier: 'b',
    index: 45,
  },
  {
    displayName: '飞鹰凝固汽油弹空袭',
    type: 'Stratagem',
    category: 'Eagle',
    tags: ['Eagle', 'fire'],
    warbondCode: 'none',
    internalName: 'eaglenapalmstrike',
    imageURL: 'eaglenapalmstrike.svg',
    antitank: false,
    tier: 'b',
    index: 46,
  },
  {
    displayName: '飞鹰烟雾空袭',
    type: 'Stratagem',
    category: 'Eagle',
    tags: ['Eagle', 'smoke'],
    warbondCode: 'none',
    internalName: 'eaglesmokestrike',
    imageURL: 'eaglesmokestrike.svg',
    antitank: false,
    tier: 'c',
    index: 47,
  },
  {
    displayName: '飞鹰110mm火箭荚舱',
    type: 'Stratagem',
    category: 'Eagle',
    tags: ['Eagle', 'at'],
    warbondCode: 'none',
    internalName: 'eagle110mmrocketpods',
    imageURL: 'eagle110mmrocketpods.svg',
    antitank: true,
    tier: 'c',
    index: 48,
  },
  {
    displayName: '飞鹰500kg炸弹',
    type: 'Stratagem',
    category: 'Eagle',
    tags: ['Eagle', 'at'],
    warbondCode: 'none',
    internalName: 'eagle500kgbomb',
    imageURL: 'eagle500kgbomb.svg',
    antitank: true,
    tier: 's',
    index: 49,
  },
  {
    displayName: '轨道精准攻击',
    type: 'Stratagem',
    category: 'Orbital',
    tags: ['Orbital', 'at'],
    warbondCode: 'none',
    internalName: 'orbitalprecisionstrike',
    imageURL: 'orbitalprecisionstrike.svg',
    antitank: true,
    tier: 'b',
    index: 50,
  },
  {
    displayName: '轨道毒气攻击',
    type: 'Stratagem',
    category: 'Orbital',
    tags: ['Orbital', 'gas'],
    warbondCode: 'none',
    internalName: 'orbitalgasstrike',
    imageURL: 'orbitalgasstrike.svg',
    antitank: false,
    tier: 'a',
    index: 51,
  },
  {
    displayName: '轨道电磁干扰打击',
    type: 'Stratagem',
    category: 'Orbital',
    tags: ['Orbital', 'stun'],
    warbondCode: 'none',
    internalName: 'orbitalemsstrike',
    imageURL: 'orbitalemsstrike.svg',
    antitank: false,
    tier: 'c',
    index: 52,
  },
  {
    displayName: '轨道烟雾空袭',
    type: 'Stratagem',
    category: 'Orbital',
    tags: ['Orbital', 'smoke'],
    warbondCode: 'none',
    internalName: 'orbitalsmokestrike',
    imageURL: 'orbitalsmokestrike.svg',
    antitank: false,
    tier: 'c',
    index: 53,
  },
  {
    displayName: '轨道空爆打击',
    type: 'Stratagem',
    category: 'Orbital',
    tags: ['Orbital'],
    warbondCode: 'none',
    internalName: 'orbitalairburststrike',
    imageURL: 'orbitalairburststrike.svg',
    antitank: false,
    tier: 'b',
    index: 54,
  },
  {
    displayName: '轨道电磁炮攻击',
    type: 'Stratagem',
    category: 'Orbital',
    tags: ['Orbital', 'at'],
    warbondCode: 'none',
    internalName: 'orbitalrailcannonstrike',
    imageURL: 'orbitalrailcannonstrike.svg',
    antitank: true,
    tier: 'b',
    index: 55,
  },
  {
    displayName: '轨道激光',
    type: 'Stratagem',
    category: 'Orbital',
    tags: ['Orbital', 'laser', 'at'],
    warbondCode: 'none',
    internalName: 'orbitallaser',
    imageURL: 'orbitallaser.svg',
    antitank: true,
    tier: 'a',
    index: 56,
  },
  {
    displayName: '轨道加特林弹幕',
    type: 'Stratagem',
    category: 'Orbital',
    tags: ['Orbital', 'bullets'],
    warbondCode: 'none',
    internalName: 'orbitalgatlingbarrage',
    imageURL: 'orbitalgatlingbarrage.svg',
    antitank: false,
    tier: 'b',
    index: 57,
  },
  {
    displayName: '轨道120mm高爆弹弹幕',
    type: 'Stratagem',
    category: 'Orbital',
    tags: ['Orbital'],
    warbondCode: 'none',
    internalName: 'orbital120mmhebarrage',
    imageURL: 'orbital120mmhebarrage.svg',
    antitank: true,
    tier: 'a',
    index: 58,
  },
  {
    displayName: '轨道380mm高爆弹弹幕',
    type: 'Stratagem',
    category: 'Orbital',
    tags: ['Orbital'],
    warbondCode: 'none',
    internalName: 'orbital380mmhebarrage',
    imageURL: 'orbital380mmhebarrage.svg',
    antitank: true,
    tier: 'a',
    index: 59,
  },
  {
    displayName: '轨道步行者弹幕',
    type: 'Stratagem',
    category: 'Orbital',
    tags: ['Orbital'],
    warbondCode: 'none',
    internalName: 'orbitalwalkingbarrage',
    imageURL: 'orbitalwalkingbarrage.svg',
    antitank: true,
    tier: 'a',
    index: 60,
  },
  {
    displayName: '轨道汽油弹弹幕',
    type: 'Stratagem',
    category: 'Orbital',
    tags: ['Orbital', 'fire'],
    warbondCode: 'none',
    internalName: 'orbitalnapalmbarrage',
    imageURL: 'orbitalnapalmbarrage.svg',
    antitank: false,
    tier: 's',
    index: 61,
  },
  {
    displayName: '特斯拉塔',
    type: 'Stratagem',
    category: 'Defense',
    tags: ['Sentry', 'arc'],
    warbondCode: 'none',
    internalName: 'teslatower',
    imageURL: 'teslatower.svg',
    antitank: false,
    tier: 'b',
    index: 62,
  },
  {
    displayName: '哨戒迫击炮',
    type: 'Stratagem',
    category: 'Defense',
    tags: ['Sentry'],
    warbondCode: 'none',
    internalName: 'mortarsentry',
    imageURL: 'mortarsentry.svg',
    antitank: false,
    tier: 'b',
    index: 63,
  },
  {
    displayName: '电磁干扰哨戒迫击炮',
    type: 'Stratagem',
    category: 'Defense',
    tags: ['Sentry', 'stun'],
    warbondCode: 'none',
    internalName: 'emsmortarsentry',
    imageURL: 'emsmortarsentry.svg',
    antitank: false,
    tier: 'c',
    index: 64,
  },
  {
    displayName: '哨戒机枪',
    type: 'Stratagem',
    category: 'Defense',
    tags: ['Sentry', 'bullets', 'ap3'],
    warbondCode: 'none',
    internalName: 'machinegunsentry',
    imageURL: 'machinegunsentry.svg',
    antitank: false,
    tier: 'a',
    index: 65,
  },
  {
    displayName: '哨戒格林炮',
    type: 'Stratagem',
    category: 'Defense',
    tags: ['Sentry', 'bullets', 'ap3'],
    warbondCode: 'none',
    internalName: 'gatlingsentry',
    imageURL: 'gatlingsentry.svg',
    antitank: false,
    tier: 'a',
    index: 66,
  },
  {
    displayName: '火焰哨戒炮',
    type: 'Stratagem',
    category: 'Defense',
    tags: ['Sentry', 'fire'],
    warbondCode: 'warbond12',
    internalName: 'aflam40flamesentry',
    imageURL: 'aflam40flamesentry.svg',
    antitank: false,
    tier: 'c',
    index: 67,
  },
  {
    displayName: '镭射哨兵塔',
    type: 'Stratagem',
    category: 'Defense',
    tags: ['Sentry', 'laser'],
    warbondCode: 'warbond17',
    internalName: 'lasersentry',
    imageURL: 'lasersentry.svg',
    antitank: true,
    tier: 'b',
    index: 68,
  },
  {
    displayName: '哨戒机炮',
    type: 'Stratagem',
    category: 'Defense',
    tags: ['Sentry', 'explosive', 'at'],
    warbondCode: 'none',
    internalName: 'autocannonsentry',
    imageURL: 'autocannonsentry.svg',
    antitank: true,
    tier: 'a',
    index: 69,
  },
  {
    displayName: '哨戒火箭炮',
    type: 'Stratagem',
    category: 'Defense',
    tags: ['Sentry', 'explosive', 'at'],
    warbondCode: 'none',
    internalName: 'rocketsentry',
    imageURL: 'rocketsentry.svg',
    antitank: true,
    tier: 'a',
    index: 70,
  },
  {
    displayName: '防护罩生成中继器',
    type: 'Stratagem',
    category: 'Defense',
    tags: ['Emplacement'],
    warbondCode: 'none',
    internalName: 'shieldgeneratorrelay',
    imageURL: 'shieldgeneratorrelay.svg',
    antitank: false,
    tier: 'c',
    index: 71,
  },
  {
    displayName: '重机枪炮台',
    type: 'Stratagem',
    category: 'Defense',
    tags: ['Emplacement', 'bullets', , 'ap4'],
    warbondCode: 'none',
    internalName: 'hmgemplacement',
    imageURL: 'hmgemplacement.svg',
    antitank: true,
    tier: 'a',
    index: 72,
  },
  {
    displayName: '反坦克炮台',
    type: 'Stratagem',
    category: 'Defense',
    tags: ['Emplacement', 'explosive', 'at'],
    warbondCode: 'warbond12',
    internalName: 'eat12antitankemplacement',
    imageURL: 'eat12antitankemplacement.svg',
    antitank: true,
    tier: 'b',
    index: 73,
  },
  {
    displayName: '掷弹兵掩体',
    type: 'Stratagem',
    category: 'Defense',
    tags: ['Emplacement', 'explosive', 'ap3'],
    warbondCode: 'none',
    internalName: 'grenadierbattlement',
    imageURL: 'grenadierbattlement.svg',
    antitank: false,
    tier: 'b',
    index: 74,
  },
  {
    displayName: '反坦克地雷',
    type: 'Stratagem',
    category: 'Defense',
    tags: ['Emplacement', 'at'],
    warbondCode: 'none',
    internalName: 'antitankmines',
    imageURL: 'antitankmines.svg',
    antitank: true,
    tier: 'c',
    index: 75,
  },
  {
    displayName: '反步兵雷区',
    type: 'Stratagem',
    category: 'Defense',
    tags: ['Emplacement'],
    warbondCode: 'none',
    internalName: 'antipersonnelminefield',
    imageURL: 'antipersonnelminefield.svg',
    antitank: false,
    tier: 'b',
    index: 76,
  },
  {
    displayName: '毒气地雷',
    type: 'Stratagem',
    category: 'Defense',
    tags: ['Emplacement', 'gas'],
    warbondCode: 'none',
    internalName: 'gasmines',
    imageURL: 'gasmines.svg',
    antitank: false,
    tier: 's',
    index: 77,
  },
  {
    displayName: '燃烧地雷',
    type: 'Stratagem',
    category: 'Defense',
    tags: ['Emplacement', 'fire'],
    warbondCode: 'none',
    internalName: 'incendiarymines',
    imageURL: 'incendiarymines.svg',
    antitank: false,
    tier: 'b',
    index: 78,
  },
  {
    displayName: '破门战锤',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons', 'melee', 'at'],
    warbondCode: 'warbond23',
    internalName: 'breachinghammer',
    imageURL: 'breachinghammer.svg',
    antitank: true,
    tier: 'b',
    index: 79,
  },
  {
    displayName: '夷平者',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons', 'at', 'expendable', 'explosive'],
    warbondCode: 'warbond23',
    internalName: 'leveller',
    imageURL: 'eat411leveller.svg',
    antitank: true,
    tier: 'a',
    index: 80,
  },
  {
    displayName: '弹链式榴弹发射器',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons', 'Backpacks', 'at', 'explosive', , 'ap4'],
    warbondCode: 'warbond23',
    internalName: 'beltfedgrenadelauncher',
    imageURL: 'beltfedgrenadelauncher.svg',
    antitank: true,
    tier: 'a',
    index: 81,
  },
  {
    displayName: '堡垒坦克',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Vehicles'],
    warbondCode: 'none',
    internalName: 'bastiontank',
    imageURL: 'bastiontank.svg',
    antitank: true,
    tier: 's',
    index: 82,
  },
  {
    displayName: '毒气哨戒迫击炮',
    type: 'Stratagem',
    category: 'Defense',
    tags: ['Sentry', 'gas'],
    warbondCode: 'warbond24',
    internalName: 'gasmortarsentry',
    imageURL: 'gasmortarsentry.svg',
    antitank: false,
    tier: 'a',
    index: 83,
  },
  {
    displayName: '火葬者',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons', 'Backpacks', 'fire', 'at'],
    warbondCode: 'warbond24',
    internalName: 'cremator',
    imageURL: 'cremator.svg',
    antitank: true,
    tier: 'a',
    index: 84,
  },

  {
    displayName: '伐木工外骨骼装甲',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Vehicles', 'fire', 'at', 'expendable', 'exosuit'],
    warbondCode: 'warbond25',
    internalName: 'exo51lumbererexosuit',
    imageURL: 'exo51lumbererexosuit.svg',
    antitank: true,
    tier: 's',
    index: 85,
  },
  {
    displayName: '突破外骨骼装甲',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Vehicles', 'expendable', 'at', 'exosuit'],
    warbondCode: 'warbond25',
    internalName: 'exo55breakthroughexosuit',
    imageURL: 'exo55breakthroughexosuit.svg',
    antitank: true,
    tier: 'a',
    index: 86,
  },
  {
    displayName: '子弹风暴',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons', 'expendable', 'bullets', 'ap2'],
    warbondCode: 'warbond25',
    internalName: 'mgx42bulletstorm',
    imageURL: 'mgx42bulletstorm.svg',
    antitank: false,
    tier: 'a',
    index: 87,
  },
];

// s: 11
// a: 28
// b: 30
// c: 9
