const THROWABLES = [
  {
    displayName: 'G-12 高爆手雷',
    type: 'Equipment',
    category: 'throwable',
    tags: ['ap4', 'explosive'],
    warbondCode: 'none',
    internalName: 'g12highexplosivegrenade',
    imageURL: 'g12highexplosivegrenade.png',
    antitank: false,
    index: 0,
    tier: 'a',
  },
  {
    displayName: 'G-6 破片手雷',
    type: 'Equipment',
    category: 'throwable',
    tags: ['ap3', 'explosive'],
    warbondCode: 'warbond3',
    internalName: 'g6fraggrenade',
    imageURL: 'g6fraggrenade.png',
    antitank: false,
    index: 1,
    tier: 'b',
  },
  {
    displayName: 'G-16 冲击雷',
    type: 'Equipment',
    category: 'throwable',
    tags: ['ap3', 'explosive'],
    warbondCode: 'warbond3',
    internalName: 'g16impactgrenade',
    imageURL: 'g16impactgrenade.png',
    antitank: false,
    index: 2,
    tier: 'a',
  },
  {
    displayName: 'G-3 烟雾弹',
    type: 'Equipment',
    category: 'throwable',
    tags: ['smoke'],
    warbondCode: 'warbond3',
    internalName: 'g3smokegrenade',
    imageURL: 'g3smokegrenade.png',
    antitank: false,
    index: 3,
    tier: 'c',
  },
  {
    displayName: 'G-10 燃烧手雷',
    type: 'Equipment',
    category: 'throwable',
    tags: ['ap3', 'explosive', 'fire'],
    warbondCode: 'warbond4',
    internalName: 'g10incendiarygrenade',
    imageURL: 'g10incendiarygrenade.png',
    antitank: false,
    index: 4,
    tier: 'b',
  },
  {
    displayName: 'G-23 眩晕手雷',
    type: 'Equipment',
    category: 'throwable',
    tags: ['stun'],
    warbondCode: 'warbond5',
    internalName: 'g23stungrenade',
    imageURL: 'g23stungrenade.png',
    antitank: false,
    index: 5,
    tier: 'a',
  },
  {
    displayName: 'G-123 铝热手雷',
    type: 'Equipment',
    category: 'throwable',
    tags: ['at'],
    warbondCode: 'warbond6',
    internalName: 'g123thermitegrenade',
    imageURL: 'g123thermitegrenade.png',
    antitank: true,
    index: 6,
    tier: 's',
  },
  {
    displayName: 'G-13 燃烧冲击雷',
    type: 'Equipment',
    category: 'throwable',
    tags: ['fire', 'ap3', 'explosive'],
    warbondCode: 'warbond7',
    internalName: 'g13incendiaryimpact',
    imageURL: 'g13incendiaryimpact.png',
    antitank: false,
    index: 7,
    tier: 'b',
  },
  {
    displayName: 'K-2 飞刀',
    type: 'Equipment',
    category: 'throwable',
    tags: ['ap3'],
    warbondCode: 'warbond8',
    internalName: 'k2throwingknife',
    imageURL: 'k2throwingknife.png',
    antitank: false,
    index: 8,
    tier: 'c',
  },
  {
    displayName: 'G-50 追踪者',
    type: 'Equipment',
    category: 'throwable',
    tags: ['ap3', 'explosive', 'guided'],
    warbondCode: 'warbond13',
    internalName: 'g50seeker',
    imageURL: 'g50seeker.png',
    antitank: false,
    index: 9,
    tier: 'a',
  },
  {
    displayName: '炸药',
    type: 'Equipment',
    category: 'throwable',
    tags: ['at', 'explosive'],
    warbondCode: 'warbond14',
    internalName: 'ted63throwabledynamite',
    imageURL: 'ted63throwabledynamite.png',
    antitank: true,
    index: 10,
    tier: 'a',
  },
  {
    displayName: 'G-142 烟火',
    type: 'Equipment',
    category: 'throwable',
    tags: ['fire', 'ap4', 'explosive'],
    warbondCode: 'warbond15',
    internalName: 'g142pyrotech',
    imageURL: 'g142pyrotech.png',
    antitank: false,
    index: 11,
    tier: 's',
  },
  {
    displayName: 'G-4 毒气手雷',
    type: 'Equipment',
    category: 'throwable',
    tags: ['gas', 'explosive'],
    warbondCode: 'warbond10',
    internalName: 'g4gasgrenade',
    imageURL: 'g4gasgrenade.png',
    antitank: false,
    index: 12,
    tier: 's',
  },
  {
    displayName: 'G-109 海胆',
    type: 'Equipment',
    category: 'throwable',
    tags: ['stun'],
    warbondCode: 'warbond16',
    internalName: 'g109urchin',
    imageURL: 'g109urchin.png',
    antitank: false,
    index: 13,
    tier: 'b',
  },
  {
    displayName: 'G-31 电弧手雷',
    type: 'Equipment',
    category: 'throwable',
    tags: ['arc'],
    warbondCode: 'warbond17',
    internalName: 'g31arc',
    imageURL: 'g31arc.png',
    antitank: false,
    index: 14,
    tier: 'b',
  },
  {
    displayName: 'G-7 菠萝手雷',
    type: 'Equipment',
    category: 'throwable',
    tags: ['ap3', 'explosive'],
    warbondCode: 'warbond20',
    internalName: 'g7pineapple',
    imageURL: 'g7pineapple.png',
    antitank: false,
    index: 15,
    tier: 'b',
  },
  {
    displayName: 'TM-01 诱饵地雷',
    type: 'Equipment',
    category: 'throwable',
    tags: ['ap4', 'explosive'],
    warbondCode: 'warbond22',
    internalName: 'tm01luremine',
    imageURL: 'tm01luremine.webp',
    antitank: false,
    index: 16,
    tier: 'b',
  },
  {
    displayName: 'G-89 烟幕弹',
    type: 'Equipment',
    category: 'throwable',
    tags: ['smoke'],
    warbondCode: 'warbond1',
    internalName: 'g89smokescreen',
    imageURL: 'g89smokescreen.png',
    antitank: false,
    index: 17,
    tier: 'c',
  },
  {
    displayName: 'G/SH-39 护盾',
    type: 'Equipment',
    category: 'throwable',
    tags: [],
    warbondCode: 'warbond23',
    internalName: 'gsh39shield',
    imageURL: 'gsh39shield.webp',
    antitank: false,
    index: 18,
    tier: 'b',
  },
  {
    displayName: 'G-48 千兆手雷',
    type: 'Equipment',
    category: 'throwable',
    tags: ['at', 'explosive'],
    warbondCode: 'warbond24',
    internalName: 'g48giga',
    imageURL: 'g48giga.webp',
    antitank: true,
    index: 19,
    tier: 'a',
  },
];

// s: 3
// a: 5
// b: 7
// c: 3
