const WARBONDS = [
  {
    displayName: "绝地潜兵动员",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond3",
    internalName: "helldiversMobilizeWB",
    imageURL: "helldiversMobilizeWB.png",
    tier: "s",
  },
  {
    displayName: "钢铁老兵",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond4",
    internalName: "steeledVeteransWB",
    imageURL: "steeledVeteransWB.png",
    tier: "a",
  },
  {
    displayName: "尖端科技",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond5",
    internalName: "cuttingEdgeWB",
    imageURL: "cuttingEdgeWB.png",
    tier: "a",
  },
  {
    displayName: "民主爆破",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond6",
    internalName: "democraticDetonationWB",
    imageURL: "democraticDetonationWB.png",
    tier: "s",
  },
  {
    displayName: "极地爱国者",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond7",
    internalName: "polarPatriotsWB",
    imageURL: "polarPatriotsWB.png",
    tier: "b",
  },
  {
    displayName: "蝰蛇突击队",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond8",
    internalName: "viperCommandosWB",
    imageURL: "viperCommandosWB.png",
    tier: "b",
  },
  {
    displayName: "自由之火",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond9",
    internalName: "freedomsFlameWB",
    imageURL: "freedomsFlameWB.png",
    tier: "b",
  },
  {
    displayName: "化学特工",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond10",
    internalName: "chemicalAgentsWB",
    imageURL: "chemicalAgentsWB.png",
    tier: "b",
  },
  {
    displayName: "真理执行者",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond11",
    internalName: "truthEnforcersWB",
    imageURL: "truthEnforcersWB.png",
    tier: "b",
  },
  {
    displayName: "都市传奇",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond12",
    internalName: "urbanLegendsWB",
    imageURL: "urbanLegendsWB.png",
    tier: "b",
  },
  {
    displayName: "自由之仆",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond13",
    internalName: "servantsOfFreedomWB",
    imageURL: "servantsOfFreedomWB.png",
    tier: "a",
  },
  {
    displayName: "边境正义",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond14",
    internalName: "borderlineJusticeWB",
    imageURL: "borderlineJusticeWB.png",
    tier: "b",
  },
  {
    displayName: "典礼大师",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond15",
    internalName: "mastersOfCeremonyWB",
    imageURL: "mastersOfCeremonyWB.png",
    tier: "c",
  },
  {
    displayName: "法律之力",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond16",
    internalName: "forceOfLawWB",
    imageURL: "forceOfLawWB.png",
    tier: "b",
  },
  {
    displayName: "对照组",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond17",
    internalName: "controlGroupWB",
    imageURL: "controlGroupWB.png",
    tier: "a",
  },
  {
    displayName: "杀戮地带",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond18",
    internalName: "killzoneWB",
    imageURL: "killzoneWB.webp",
    tier: "b",
  },
  {
    displayName: "ODST",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond19",
    internalName: "odstWB",
    imageURL: "odstWB.png",
    tier: "b",
  },
  {
    displayName: "尘暴恶魔",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond20",
    internalName: "dustdevilsWB",
    imageURL: "dustdevilsWB.png",
    tier: "b",
  },
  {
    displayName: "蟒蛇突击队",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond21",
    internalName: "pythoncommandosWB",
    imageURL: "pythoncommandosWB.webp",
    tier: "b",
  },
  {
    displayName: "机密军团",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond22",
    internalName: "redactedregimentWB",
    imageURL: "redactedRegimentWB.webp",
    tier: "b",
  },
  {
    displayName: "攻城突破者",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond23",
    internalName: "siegebreakersWB",
    imageURL: "siegeBreakersWB.webp",
    tier: "b",
  },
  {
    displayName: "固守师团",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond24",
    internalName: "entrenchedDivisionWB",
    imageURL: "entrenchedDivisionWB.webp",
    tier: "b",
  },
  {
    displayName: "机甲专家",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond25",
    internalName: "exoExpertsWB",
    imageURL: "exoExpertsWB.webp",
    tier: "b",
  },
];
